import type { SectionStatusInfo } from '@/components/reference-status';

export const appShellSectionStatus = {
  currentUser: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/me' },
      { contract: 'deferred', method: 'PATCH', path: '/api/v2/me/preferences' },
    ],
    evidence: 'Verified with Playwright visual target and pnpm check.',
    fieldsUsed: [
      'displayName',
      'name',
      'email',
      'photo',
      'summary.unreadNotificationCount',
      'summary.pendingRequestCount',
    ],
    id: 'shared-shell-current-user-avatar',
    page: 'Shared App Shell',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'workspace_resource_hub_shared.js/css',
    section: 'Current user/avatar',
  },
  externalLinks: {
    evidence: 'Verified against reference service outlinks.',
    fieldsUsed: [
      'Static DEJ chatbot link title, description, icon, and href',
      'Static HEANS link title, description, icon, and href',
      'Static HEVPDS link title, description, icon, and href',
    ],
    id: 'shared-shell-external-links',
    page: 'Shared App Shell',
    progress: 'verified',
    readiness: 'Static-only',
    reference: 'workspace_resource_hub_shared.js/css',
    section: 'External service links',
  },
  globalSearch: {
    apis: [
      { contract: 'missing', method: 'GET', path: '/api/v2/search?q=&types=projects,domains,...' },
      { contract: 'missing', method: 'GET', path: '/api/v2/tags (paged)' },
      { contract: 'missing', method: 'GET', path: '/api/v2/hashtags (paged)' },
    ],
    blockers: [
      'Missing Launchpad Search route decision plus accepted response contracts for GET /api/v2/search?q=&types=projects,domains,..., GET /api/v2/tags (paged), and GET /api/v2/hashtags (paged); global search cannot be verified.',
    ],
    id: 'shared-shell-global-search',
    nextAction: 'Provide route decision and accepted search response contracts.',
    page: 'Shared App Shell',
    progress: 'blocked',
    readiness: 'Blocked',
    reference: 'workspace_resource_hub_shared.js, portal_launchpad_search.html',
    section: 'Global search',
  },
  notifications: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/me/notifications (paged)' }],
    evidence: 'Verified with Playwright visual target and pnpm check.',
    fieldsUsed: [
      'items[].title',
      'items[].message',
      'items[].status',
      'items[].isUnread',
      'page.total',
    ],
    id: 'shared-shell-notifications',
    page: 'Shared App Shell',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'workspace_resource_hub_shared.js/css',
    section: 'Notifications',
  },
  serviceMenu: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/service-menu' }],
    evidence:
      'Verified with user-provided sample payload accepted for GET /api/v2/launchpad/service-menu; focused service-menu visual target, broader pnpm visual, and pnpm check passed.',
    fieldsUsed: [
      'groups[].title',
      'groups[].links[].label',
      'groups[].links[].description',
      'groups[].links[].icon',
      'groups[].links[].href',
      'externalLinks[].title',
      'externalLinks[].href',
    ],
    id: 'shared-shell-service-menu',
    page: 'Shared App Shell',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'workspace_resource_hub_shared.js/css, portal_launchpad.html',
    section: 'Service menu',
  },
  topbar: {
    evidence: 'Verified with Playwright visual target and pnpm check.',
    fieldsUsed: [
      'Static brand logo mark and Workspace text',
      'Static service-menu trigger placement',
      'Static search input placement',
      'Static notification and avatar affordance placement',
    ],
    id: 'shared-shell-topbar',
    page: 'Shared App Shell',
    progress: 'verified',
    readiness: 'Static-only',
    reference: 'workspace_resource_hub_shared.js/css, portal_launchpad.html',
    section: 'Topbar brand/layout',
  },
} satisfies Record<string, SectionStatusInfo>;
