import type { SectionStatusInfo } from '@/components/reference-status';

export const appGallerySectionStatus = {
  categoryTabs: {
    apis: [{ contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/categories' }],
    fieldsUsed: [
      'defaultCategory',
      'items[].id',
      'items[].label',
      'items[].description',
      'items[].count',
    ],
    id: 'app-gallery-category-tabs',
    nextAction:
      'Run focused Playwright reference verification for this section, then run the broader visual suite before marking Verified.',
    page: 'App Gallery',
    progress: 'implemented',
    readiness: 'Already implemented',
    reference: 'dej_app_store.html',
    section: 'Category tabs',
  },
  collections: {
    apis: [
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/categories' },
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/featured' },
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/related-ai' },
    ],
    fieldsUsed: [
      'apps[].category',
      'apps[].categoryLabel',
      'apps[].title',
      'apps[].subtitle',
      'apps[].icon',
      'apps[].iconColor',
    ],
    id: 'app-gallery-collections',
    nextAction:
      'Run focused Playwright reference verification for this section, then run the broader visual suite before marking Verified.',
    page: 'App Gallery',
    progress: 'implemented',
    readiness: 'Already implemented',
    reference: 'dej_app_store.html',
    section: 'Collections',
  },
  highlights: {
    apis: [
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/featured' },
      { contract: 'missing', method: 'GET', path: '/api/v2/app-gallery/apps/:slug' },
    ],
    blockers: [
      'Missing accepted response contract for GET /api/v2/app-gallery/apps/:slug, so highlighted card detail behavior cannot be verified.',
      'Highlighted card click/open behavior still needs reference verification after the app detail contract is available.',
    ],
    fieldsUsed: [
      'items[].title',
      'items[].subtitle',
      'items[].summary',
      'items[].tags',
      'items[].installTargetLabel',
      'items[].capabilities.canPreview',
    ],
    id: 'app-gallery-highlights',
    nextAction: 'Provide/approve app detail contract and verify highlighted card behavior.',
    page: 'App Gallery',
    progress: 'in-progress',
    readiness: 'Blocked',
    reference: 'dej_app_store.html',
    section: 'Curated highlights',
  },
  heroRail: {
    apis: [
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/hero' },
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/apps (paged)' },
    ],
    fieldsUsed: [
      'apps[].title',
      'apps[].subtitle',
      'apps[].summary',
      'apps[].categoryLabel',
      'apps[].icon',
      'apps[].iconColor',
    ],
    id: 'app-gallery-hero-rail',
    nextAction:
      'Run focused Playwright reference verification for this section, then run the broader visual suite before marking Verified.',
    page: 'App Gallery',
    progress: 'implemented',
    readiness: 'Already implemented',
    reference: 'dej_app_store.html',
    section: 'Hero rail',
  },
  pageIntro: {
    apis: [
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/hero' },
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/categories' },
    ],
    fieldsUsed: [
      'title',
      'subtitle',
      'stats[].label',
      'stats[].value',
      'stats[].note',
      'categories.items[].label',
      'categories.items[].description',
      'categories.items[].count',
    ],
    id: 'app-gallery-page-intro',
    nextAction:
      'Run focused Playwright reference verification for this section, then run the broader visual suite before marking Verified.',
    page: 'App Gallery',
    progress: 'implemented',
    readiness: 'Already implemented',
    reference: 'dej_app_store.html',
    section: 'Page head / intro',
  },
  registeredApps: {
    apis: [
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/apps (paged)' },
      { contract: 'missing', method: 'GET', path: '/api/v2/app-gallery/apps/:slug' },
      { contract: 'missing', method: 'POST', path: '/api/v2/app-gallery/apps/:slug/install' },
    ],
    blockers: [
      'Missing accepted response contract for GET /api/v2/app-gallery/apps/:slug, so registered app card detail behavior cannot be verified.',
      'Missing accepted response contract and mock route for POST /api/v2/app-gallery/apps/:slug/install, so the install action flow remains blocked.',
    ],
    fieldsUsed: [
      'items[].title',
      'items[].subtitle',
      'items[].summary',
      'items[].tags',
      'items[].installTargetLabel',
      'items[].capabilities.canInstall',
      'items[].capabilities.canPreview',
    ],
    id: 'app-gallery-registered-apps',
    nextAction: 'Provide app detail/install contract and complete action flow.',
    page: 'App Gallery',
    progress: 'in-progress',
    readiness: 'Blocked',
    reference: 'dej_app_store.html',
    section: 'Registered app cards',
  },
  sideRail: {
    apis: [
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/apps (paged)' },
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/featured' },
      { contract: 'fixture-backed', method: 'GET', path: '/api/v2/app-gallery/categories' },
    ],
    fieldsUsed: [
      'apps[].title',
      'apps[].subtitle',
      'apps[].summary',
      'apps[].categoryLabel',
      'apps[].iconColor',
    ],
    id: 'app-gallery-side-rail',
    nextAction:
      'Run focused Playwright reference verification for this section, then run the broader visual suite before marking Verified.',
    page: 'App Gallery',
    progress: 'implemented',
    readiness: 'Already implemented',
    reference: 'dej_app_store.html',
    section: 'Side rail summaries',
  },
} satisfies Record<string, SectionStatusInfo>;
