import type { SectionStatusInfo } from '@/components/reference-status';

export const appGallerySectionStatus = {
  categoryTabs: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/categories' }],
    evidence: 'User-provided sample payload accepted for category items and default category.',
    fieldsUsed: [
      'defaultCategory',
      'items[].id',
      'items[].label',
      'items[].description',
      'items[].count',
    ],
    id: 'app-gallery-category-tabs',
    nextAction:
      'No action; verified against the current reference with focused and scoped App Gallery visual targets, and project checks passed.',
    page: 'App Gallery',
    progress: 'verified',
    readiness: 'Already implemented',
    reference: 'dej_app_gallery.html',
    section: 'Category tabs',
  },
  collections: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/categories' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/featured' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/related-ai' },
    ],
    evidence:
      'User-provided sample payloads accepted for categories, featured apps, related AI items, and the current published-project app list.',
    fieldsUsed: [
      'apps[].category',
      'apps[].categoryLabel',
      'apps[].title',
      'apps[].subtitle',
      'apps[].icon',
      'apps[].iconColor',
      'apps[].action.href',
    ],
    id: 'app-gallery-collections',
    nextAction:
      'No action; verified against the current reference with focused and scoped App Gallery visual targets, and project checks passed.',
    page: 'App Gallery',
    progress: 'verified',
    readiness: 'Already implemented',
    reference: 'dej_app_gallery.html',
    section: 'Collections',
  },
  highlights: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/featured' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/apps/:slug' },
    ],
    evidence:
      'User-provided sample payloads accepted for featured app cards and app detail responses.',
    fieldsUsed: [
      'items[].title',
      'items[].subtitle',
      'items[].summary',
      'items[].recommendationReason',
      'items[].tags',
      'items[].installTargetLabel',
      'items[].lifecycleLabel',
      'items[].capabilities.canPreview',
      'items[].action.href',
    ],
    id: 'app-gallery-highlights',
    nextAction:
      'No action; verified against the current reference with focused and scoped App Gallery visual targets, and project checks passed.',
    page: 'App Gallery',
    progress: 'verified',
    readiness: 'Already implemented',
    reference: 'dej_app_gallery.html',
    section: 'Curated highlights',
  },
  heroRail: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/hero' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/apps (paged)' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/related-ai' },
    ],
    evidence:
      'User-provided sample payloads accepted for hero data, paged app list items, and related AI items.',
    fieldsUsed: [
      'apps[].title',
      'apps[].subtitle',
      'apps[].summary',
      'apps[].recommendationReason',
      'apps[].categoryLabel',
      'apps[].icon',
      'apps[].iconColor',
      'apps[].lifecycleLabel',
      'relatedAi[].title',
      'relatedAi[].subtitle',
      'relatedAi[].category',
      'relatedAi[].href',
    ],
    id: 'app-gallery-hero-rail',
    nextAction:
      'No action; verified against the current reference with focused and scoped App Gallery visual targets, and project checks passed.',
    page: 'App Gallery',
    progress: 'verified',
    readiness: 'Already implemented',
    reference: 'dej_app_gallery.html',
    section: 'Hero rail',
  },
  pageIntro: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/hero' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/categories' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/apps (paged)' },
    ],
    evidence:
      'User-provided sample payloads accepted for hero stats, categories, and paged app list totals.',
    fieldsUsed: [
      'title',
      'subtitle',
      'stats[].label',
      'stats[].value',
      'stats[].note',
      'categories.items[].label',
      'categories.items[].description',
      'categories.items[].count',
      'page.total',
    ],
    id: 'app-gallery-page-intro',
    nextAction:
      'No action; verified against the current reference with focused and scoped App Gallery visual targets, and project checks passed.',
    page: 'App Gallery',
    progress: 'verified',
    readiness: 'Already implemented',
    reference: 'dej_app_gallery.html',
    section: 'Page head / intro',
  },
  registeredApps: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/apps (paged)' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/apps/:slug' },
    ],
    evidence:
      'User-provided sample payloads accepted for the paged development app list, workspace empty category response, and all six visible app detail responses.',
    fieldsUsed: [
      'items[].title',
      'items[].subtitle',
      'items[].summary',
      'items[].tags',
      'items[].installTargetLabel',
      'items[].capabilities.canInstall',
      'items[].capabilities.canPreview',
      'items[].capabilities.canOpen',
      'items[].lifecycleLabel',
      'items[].recommendationReason',
      'items[].action.href',
    ],
    id: 'app-gallery-registered-apps',
    nextAction:
      'No action; verified against the current reference with focused and scoped App Gallery visual targets, and project checks passed.',
    page: 'App Gallery',
    progress: 'verified',
    readiness: 'Already implemented',
    reference: 'dej_app_gallery.html',
    section: 'Registered app cards',
  },
  sideRail: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/apps (paged)' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/featured' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/app-gallery/categories' },
    ],
    evidence: 'User-provided sample payloads accepted for app list, featured apps, and categories.',
    fieldsUsed: [
      'apps[].title',
      'apps[].subtitle',
      'apps[].summary',
      'apps[].categoryLabel',
      'apps[].iconColor',
      'apps[].lifecycleLabel',
    ],
    id: 'app-gallery-side-rail',
    nextAction:
      'No action; verified against the current reference with focused and scoped App Gallery visual targets, and project checks passed.',
    page: 'App Gallery',
    progress: 'verified',
    readiness: 'Already implemented',
    reference: 'dej_app_gallery.html',
    section: 'Side rail summaries',
  },
} satisfies Record<string, SectionStatusInfo>;
