import type { SectionStatusInfo } from '@/components/reference-status';

export const permissionHubSectionStatus = {
  blockedSections: {
    apis: [
      { contract: 'missing', method: 'POST', path: '/api/v2/permissions/realms' },
      { contract: 'missing', method: 'DELETE', path: '/api/v2/permissions/realms/:id' },
      { contract: 'missing', method: 'GET', path: '/api/v2/permissions/realms/:id' },
      { contract: 'missing', method: 'GET', path: '/api/v2/permissions/realms/:id/roles' },
      { contract: 'missing', method: 'GET', path: '/api/v2/permissions/requests (paged)' },
      { contract: 'missing', method: 'POST', path: '/api/v2/permissions/realms/:id/requests' },
    ],
    blockers: [
      'Missing accepted response contracts for POST /api/v2/permissions/realms, DELETE /api/v2/permissions/realms/:id, GET /api/v2/permissions/realms/:id, and GET /api/v2/permissions/realms/:id/roles, so create, delete, detail, and role management controls stay disabled.',
      'Missing accepted response contracts for GET /api/v2/permissions/requests (paged) and POST /api/v2/permissions/realms/:id/requests, so the request inbox and request submission flow remain blocked.',
    ],
    id: 'permission-hub-blocked-sections',
    nextAction: 'Provide documented contracts, sample payloads, or approved fixtures.',
    page: 'Permission Hub',
    progress: 'blocked',
    readiness: 'Blocked',
    reference: 'workspace_permission_hub.html',
    section: 'Action flows / request inbox',
  },
  cards: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/permissions/realms (paged)' },
      { contract: 'missing', method: 'POST', path: '/api/v2/permissions/realms' },
      { contract: 'missing', method: 'DELETE', path: '/api/v2/permissions/realms/:id' },
      { contract: 'missing', method: 'GET', path: '/api/v2/permissions/realms/:id' },
      { contract: 'missing', method: 'POST', path: '/api/v2/permissions/realms/:id/requests' },
    ],
    blockers: [
      'Create, delete, detail, and request controls are disabled because the exact action response contracts are missing.',
    ],
    evidence:
      'Read-only realm card bodies render from the accepted list payload: name, kind, status, members, roles, project bindings, capabilities, and current-user roles.',
    fieldsUsed: [
      'items[].id',
      'items[].name',
      'items[].description',
      'items[].kind',
      'items[].status',
      'items[].memberCount',
      'items[].projectCount',
      'items[].boundProjects[].label',
      'items[].boundProjects[].role',
      'items[].roles[].name',
      'items[].roles[].memberCount',
      'items[].capabilities.canApprove',
      'items[].currentUserRoles[]',
      'page.total',
    ],
    id: 'permission-hub-realm-cards',
    nextAction: 'Provide accepted action/detail/request contracts before enabling card controls.',
    page: 'Permission Hub',
    progress: 'in-progress',
    readiness: 'Blocked',
    reference: 'workspace_permission_hub.html',
    section: 'Realm cards',
  },
  filters: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/permissions/realms/filters' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/permissions/realms (paged)' },
    ],
    evidence:
      'Accepted filters/list payloads and route wiring render the reference kind filter chips; zero-count kinds are hidden like the loaded reference state.',
    fieldsUsed: ['kinds[].value', 'kinds[].count', 'page.total'],
    id: 'permission-hub-filters',
    page: 'Permission Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_permission_hub.html',
    section: 'Filter bar',
  },
  guideLinks: {
    apis: [
      {
        contract: 'accepted',
        method: 'GET',
        path: '/api/v2/panels/guide-links?surface=permissions',
      },
    ],
    evidence: 'React renders the accepted guide-link panel payload; visual acceptance is pending.',
    fieldsUsed: ['title', 'description', 'rows[].title', 'rows[].href', 'footerLink.href'],
    id: 'permission-hub-guide-links',
    page: 'Permission Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_permission_hub.html',
    section: 'Guide links',
  },
  hero: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/permissions/realms/stats' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/permissions/realms/filters' },
    ],
    evidence:
      'React renders the current reference hero summary from accepted stats and filter fields. Create action remains disabled under the action-flow blocker.',
    fieldsUsed: [
      'totalRealms',
      'totalMembers',
      'boundProjectCount',
      'pendingRequests',
      'manageableRealms',
      'filters.kinds[].count',
    ],
    id: 'permission-hub-hero',
    page: 'Permission Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_permission_hub.html',
    section: 'Hero summary',
  },
  requestInbox: {
    apis: [
      { contract: 'missing', method: 'GET', path: '/api/v2/permissions/requests (paged)' },
      { contract: 'missing', method: 'GET', path: '/api/v2/permissions/requests/:reqId' },
      { contract: 'missing', method: 'POST', path: '/api/v2/permissions/realms/:id/requests' },
      { contract: 'missing', method: 'POST', path: '/api/v2/permissions/requests/:reqId/approve' },
      { contract: 'missing', method: 'POST', path: '/api/v2/permissions/requests/:reqId/reject' },
    ],
    blockers: [
      'Missing accepted response contract for GET /api/v2/permissions/requests (paged), so the current request list cannot render API-backed rows.',
      'Missing accepted response contracts for request create, approve, reject, and detail endpoints, so request actions stay disabled.',
    ],
    id: 'permission-hub-request-inbox',
    nextAction: 'Provide accepted request inbox and request action response contracts.',
    page: 'Permission Hub',
    progress: 'blocked',
    readiness: 'Blocked',
    reference: 'workspace_permission_hub.html',
    section: 'Request inbox rail',
  },
  tips: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/panels/tips?surface=permissions' },
    ],
    evidence: 'React renders the accepted tips panel payload; visual acceptance is pending.',
    fieldsUsed: ['title', 'description', 'rows[].title', 'rows[].meta', 'footerLink.href'],
    id: 'permission-hub-tips',
    page: 'Permission Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_permission_hub.html',
    section: 'Permission operation tips',
  },
} satisfies Record<string, SectionStatusInfo>;
