import type { SectionStatusInfo } from '@/components/reference-status';

export const agentHubSectionStatus = {
  cards: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/agents?cursor=&sort=&limit=&q=' },
      { contract: 'missing', method: 'GET', path: '/api/v2/agents/:id' },
      { contract: 'missing', method: 'POST', path: '/api/v2/agents' },
      { contract: 'missing', method: 'PATCH', path: '/api/v2/agents/:id' },
      { contract: 'missing', method: 'DELETE', path: '/api/v2/agents/:id' },
      { contract: 'missing', method: 'POST', path: '/api/v2/agents/:id/open' },
      { contract: 'missing', method: 'GET', path: '/api/v2/agents/:id/runtime' },
      { contract: 'missing', method: 'GET', path: '/api/v2/agents/:id/tools' },
    ],
    blockers: [
      'Missing accepted response contract for GET /api/v2/agents/:id, so detail navigation remains disabled.',
      'Missing accepted response contracts for create, edit, delete, open, runtime detail, and tool inventory actions; card action buttons remain disabled.',
    ],
    evidence: 'Read-only agent cards use the accepted paged agent list payload.',
    fieldsUsed: [
      'items[].id',
      'items[].name',
      'items[].summary',
      'items[].type',
      'items[].typeLabel',
      'items[].status',
      'items[].statusLabel',
      'items[].runtime.provider',
      'items[].runtime.statusLabel',
      'items[].runtime.url',
      'items[].model.primary',
      'items[].workflow.stepCount',
      'items[].approval.required',
      'items[].auth.mode',
      'items[].toolCount',
      'items[].owner.name',
      'items[].openUrl',
      'items[].capabilities.canOpen',
      'page.total',
    ],
    id: 'agent-hub-cards',
    nextAction: 'Provide or approve contracts for the listed agent detail and action endpoints.',
    page: 'Workflow / Agent Hub',
    progress: 'in-progress',
    readiness: 'Blocked',
    reference: 'workspace_agent_hub.html',
    section: 'Agent cards',
  },
  guideLinks: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/panels/guide-links?surface=agents' },
    ],
    evidence: 'User-provided sample payload is accepted and rendered through React Query.',
    fieldsUsed: [
      'title',
      'description',
      'rows[].title',
      'rows[].meta',
      'rows[].href',
      'footerLink.href',
    ],
    id: 'agent-hub-guide-links',
    page: 'Workflow / Agent Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_agent_hub.html',
    section: 'Guide links',
  },
  heroFilters: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/agents?cursor=&sort=&limit=&q=' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/agents/stats' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/agents/filters' },
      { contract: 'missing', method: 'POST', path: '/api/v2/agents' },
    ],
    blockers: [
      'Missing accepted response contract and behavior for POST /api/v2/agents; the create CTA remains disabled.',
    ],
    evidence:
      'Summary values and filter chips use the accepted agent stats, filters, and list payloads.',
    fieldsUsed: [
      'data.cards[].id',
      'data.cards[].label',
      'data.cards[].value',
      'data.cards[].note',
      'data.types[].id',
      'data.types[].label',
      'data.types[].count',
      'data.statuses[].id',
      'data.statuses[].label',
      'data.statuses[].count',
      'page.total',
    ],
    id: 'agent-hub-hero-filters',
    nextAction: 'Provide the agent create contract and behavior decision.',
    page: 'Workflow / Agent Hub',
    progress: 'in-progress',
    readiness: 'Blocked',
    reference: 'workspace_agent_hub.html',
    section: 'Hero summary / filters',
  },
  modelingTips: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/agents/panels/models' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/panels/tips?surface=agents' },
    ],
    evidence: 'User-provided sample payloads are accepted and rendered through React Query.',
    fieldsUsed: [
      'model.title',
      'model.description',
      'model.rows[].title',
      'model.rows[].meta',
      'tips.title',
      'tips.description',
      'tips.rows[].title',
      'tips.rows[].meta',
      'tips.footerLink.href',
    ],
    id: 'agent-hub-modeling-tips',
    page: 'Workflow / Agent Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_agent_hub.html',
    section: 'Agent modeling / tips',
  },
  runtimeRail: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/agents/panels/runtime-status' }],
    evidence: 'User-provided sample payload is accepted and rendered through React Query.',
    fieldsUsed: [
      'title',
      'description',
      'rows[].id',
      'rows[].title',
      'rows[].meta',
      'rows[].pill.label',
      'rows[].pill.tone',
    ],
    id: 'agent-hub-runtime-rail',
    page: 'Workflow / Agent Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_agent_hub.html',
    section: 'Runtime rail',
  },
} satisfies Record<string, SectionStatusInfo>;
