import type { SectionStatusInfo } from '@/components/reference-status';

export const databaseHubSectionStatus = {
  cards: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/databases?cursor=&sort=&limit=&q=' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/databases/:id' },
      { contract: 'accepted', method: 'POST', path: '/api/v2/databases' },
      { contract: 'accepted', method: 'POST', path: '/api/v2/databases/:id/restart' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/databases/:id/bindings' },
    ],
    evidence:
      'Accepted user-provided contracts support card rendering, binding rows, create response state, restart request state, and detail refresh after restart.',
    fieldsUsed: [
      'items[].name',
      'items[].engine',
      'items[].version',
      'items[].status',
      'items[].summary',
      'items[].endpoint',
      'items[].usage.storageLabel',
      'items[].bindingCount',
      'items[].health.label',
      'items[].owner.displayName',
      'bindings.items[].targetType',
      'bindings.items[].label',
      'bindings.items[].description',
      'create.data.name',
      'create.data.engine',
      'create.data.usage.storageLabel',
      'create.data.health.label',
      'restart.data.status',
    ],
    id: 'database-hub-cards',
    page: 'Database Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_database_hub.html',
    section: 'Database cards',
  },
  filters: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/databases/filters' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/databases?cursor=&sort=&limit=&q=' },
    ],
    evidence:
      'Accepted user-provided filters payload drives reference category filter chips and loaded counts.',
    fieldsUsed: ['engines[].value', 'engines[].count', 'statuses[].value', 'page.total'],
    id: 'database-hub-filters',
    page: 'Database Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_database_hub.html',
    section: 'Filter bar',
  },
  guideLinks: {
    apis: [
      {
        contract: 'accepted',
        method: 'GET',
        path: '/api/v2/panels/guide-links?surface=databases',
      },
    ],
    evidence:
      'Focused Playwright target, broader visual suite, and project checks passed with the accepted guide-links payload.',
    fieldsUsed: ['title', 'description', 'rows[].title', 'rows[].href', 'footerLink.href'],
    id: 'database-hub-guide-links',
    page: 'Database Hub',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'workspace_database_hub.html',
    section: 'Guide links',
  },
  healthRail: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/databases/panels/health' }],
    evidence:
      'React renders the accepted health panel payload with the current reference live-snapshot overview labels and item health messages; visual acceptance remains pending.',
    fieldsUsed: [
      'summary.total',
      'summary.healthy',
      'summary.degraded',
      'summary.unknown',
      'items[].name',
      'items[].health.label',
      'items[].health.message',
    ],
    id: 'database-hub-health-rail',
    page: 'Database Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_database_hub.html',
    section: 'Health rail',
  },
  hero: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/databases/stats' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/databases/filters' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/databases/panels/health' },
      { contract: 'accepted', method: 'POST', path: '/api/v2/databases' },
      { contract: 'deferred', method: 'GET', path: '/api/v2/search?q=&types=projects,domains,...' },
    ],
    blockers: [
      'Missing accepted response contract for shared global search, so cross-resource search remains deferred to the app shell/search work.',
    ],
    evidence:
      'Accepted user-provided stats, filters, health panel, and create payloads support the contract-driven summary and create CTA.',
    fieldsUsed: [
      'totalDatabases',
      'runningCount',
      'issueCount',
      'bindingCount',
      'engines[].count',
      'statuses[].count',
      'health.summary.healthy',
      'health.summary.degraded',
      'health.summary.unknown',
    ],
    id: 'database-hub-hero',
    nextAction: 'Use /ref-verify for visual acceptance; shared global search remains separate.',
    page: 'Database Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_database_hub.html',
    section: 'Hero summary',
  },
  tips: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/panels/tips?surface=databases' }],
    evidence:
      'Focused Playwright target, broader visual suite, and project checks passed with the accepted tips payload.',
    fieldsUsed: ['title', 'description', 'rows[].title', 'rows[].meta', 'footerLink.href'],
    id: 'database-hub-tips',
    page: 'Database Hub',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'workspace_database_hub.html',
    section: 'Database operation tips',
  },
} satisfies Record<string, SectionStatusInfo>;
