import path from 'node:path';
import { fileURLToPath } from 'node:url';

export type VisualTarget = {
  expectedReactDetailText?: string[];
  expectedReactAttributes?: VisualAttributeExpectation[];
  expectedReactLocatorText?: VisualLocatorTextExpectation[];
  expectedReactText: string[];
  expectedReactLinks?: VisualLinkExpectation[];
  expectedReactRequests?: string[];
  expectedReferenceDetailText?: string[];
  expectedReferenceAttributes?: VisualAttributeExpectation[];
  expectedReferenceLocatorText?: VisualLocatorTextExpectation[];
  expectedReferenceText: string[];
  expectedReferenceLinks?: VisualLinkExpectation[];
  expectedReferenceRequests?: string[];
  name: string;
  reactDetailActions?: VisualAction[];
  reactDetailSelector?: string;
  reactActions?: VisualAction[];
  reactSelector: string;
  referenceDetailActions?: VisualAction[];
  referenceDetailSelector?: string;
  referenceActions?: VisualAction[];
  referenceFile: string;
  referenceSelector: string;
  referenceUrl: string;
  route: string;
  slug: string;
  timeout?: number;
  trackerRow: string;
};

export type VisualAttributeExpectation = {
  attribute: string;
  label: string;
  selector: string;
  value: string;
};

export type VisualLinkExpectation = {
  href: string;
  label: string;
  rel?: string;
  target?: string;
};

export type VisualLocatorTextExpectation = {
  label: string;
  selector: string;
  text: string;
};

export type VisualAction =
  | 'open-app-gallery-featured-detail'
  | 'open-app-gallery-collection-detail'
  | 'open-app-gallery-registered-detail'
  | 'open-database-create-dialog'
  | 'open-domain-create-dialog'
  | 'open-notifications'
  | 'open-service-menu'
  | 'submit-app-gallery-install';

const rootDirectory = fileURLToPath(new URL('../../', import.meta.url));
const aboutDejReferenceFile = path.join(rootDirectory, 'reference', 'about_dej.html');
const agentHubReferenceFile = path.join(rootDirectory, 'reference', 'workspace_agent_hub.html');
const appGalleryReferenceFile = path.join(rootDirectory, 'reference', 'dej_app_gallery.html');
const bucketHubReferenceFile = path.join(rootDirectory, 'reference', 'workspace_s3_hub.html');
const consoleHubReferenceFile = path.join(rootDirectory, 'reference', 'workspace_tools_hub.html');
const databaseHubReferenceFile = path.join(
  rootDirectory,
  'reference',
  'workspace_database_hub.html',
);
const domainHubReferenceFile = path.join(rootDirectory, 'reference', 'workspace_domain_hub.html');
const launchpadReferenceFile = path.join(rootDirectory, 'reference', 'portal_launchpad.html');
const permissionHubReferenceFile = path.join(
  rootDirectory,
  'reference',
  'workspace_permission_hub.html',
);

const referenceBaseUrl = process.env.VISUAL_REFERENCE_BASE_URL ?? 'http://127.0.0.1:3000/reference';

function toReferenceUrl(referenceFile: string) {
  return `${referenceBaseUrl}/${path.basename(referenceFile)}`;
}

export const visualTargets: VisualTarget[] = [
  {
    expectedReactText: [
      'About DEJ',
      'Development Experience Journey',
      '고객중심의 개발 플랫폼 / 고객경험 혁신을 위한 일하는 방식의 변화',
      'Get Started',
      'CEJ·DEJ 파이프라인',
      'CEJ 데이터가 DEJ 실행으로 바뀌는 흐름',
      'Customer Experience Journey',
      '고객경험 영역 데이터',
      'Apps · AI · Projects',
      'DEJ 콘셉트의 변화',
      '고객경험 여정에서 출발',
      'Core Ideas',
      'Connectivity',
      'Core Value',
      'Continue in AX Studio',
      'App Gallery',
      'AI Gallery',
      'Project / Publish',
      '지원 챗봇',
    ],
    expectedReferenceText: [
      'About DEJ',
      'Development Experience Journey',
      '고객중심의 개발 플랫폼 / 고객경험 혁신을 위한 일하는 방식의 변화',
      'Get Started',
      'CEJ·DEJ 파이프라인',
      'CEJ 데이터가 DEJ 실행으로 바뀌는 흐름',
      'Customer Experience Journey',
      '고객경험 영역 데이터',
      'Apps · AI · Projects',
      'DEJ 콘셉트의 변화',
      '고객경험 여정에서 출발',
      'Core Ideas',
      'Connectivity',
      'Core Value',
      'Continue in AX Studio',
      'App Gallery',
      'AI Gallery',
      'Project / Publish',
      '지원 챗봇',
    ],
    name: 'About DEJ full page',
    reactSelector: '#root > div',
    referenceFile: aboutDejReferenceFile,
    referenceSelector: '.page',
    referenceUrl: toReferenceUrl(aboutDejReferenceFile),
    route: '/docs/about-dej',
    slug: 'about-dej-full-page',
    trackerRow: 'About DEJ :: Full page',
  },
  {
    expectedReactText: [
      'About DEJ',
      'Development Experience Journey',
      '고객중심의 개발 플랫폼 / 고객경험 혁신을 위한 일하는 방식의 변화',
      'Get Started',
      'CEJ·DEJ 파이프라인',
      '히스토리',
      '3C 2S 고객경험 영역의 데이터',
      'Core Value',
      'Connectivity',
      'Customization',
      'Care',
      'Servitization',
      'Sustainability',
      '신속한 탐지',
      '빠른의사결정',
      '품질무결성',
      '제때개발',
      '구성원만족도',
      'CEJ',
      'DEJ',
    ],
    expectedReferenceText: [
      'About DEJ',
      'Development Experience Journey',
      '고객중심의 개발 플랫폼 / 고객경험 혁신을 위한 일하는 방식의 변화',
      'Get Started',
      'CEJ·DEJ 파이프라인',
      '히스토리',
      '3C 2S 고객경험 영역의 데이터',
      'Core Value',
      'Connectivity',
      'Customization',
      'Care',
      'Servitization',
      'Sustainability',
      '신속한 탐지',
      '빠른의사결정',
      '품질무결성',
      '제때개발',
      '구성원만족도',
      'CEJ',
      'DEJ',
    ],
    name: 'About DEJ static hero',
    reactSelector:
      "xpath=//*[normalize-space()='About DEJ']/ancestor::*[.//*[normalize-space()='Get Started'] and .//*[normalize-space()='CEJ'] and .//*[normalize-space()='DEJ']][1]",
    referenceFile: aboutDejReferenceFile,
    referenceSelector: '.portal-hero',
    referenceUrl: toReferenceUrl(aboutDejReferenceFile),
    route: '/docs/about-dej',
    slug: 'about-dej-static-hero',
    trackerRow: 'About DEJ :: Static hero',
  },
  {
    expectedReactText: [
      'Pipeline',
      'CEJ 데이터가 DEJ 실행으로 바뀌는 흐름',
      'Customer Experience Journey',
      '고객경험 영역 데이터',
      'Development Experience Journey',
      'Apps · AI · Projects',
      '제때개발과 품질 개선',
      '빠른 의사결정과 품질무결성을 바탕으로 필요한 순간에 필요한 기능을 제공합니다.',
    ],
    expectedReferenceText: [
      'Pipeline',
      'CEJ 데이터가 DEJ 실행으로 바뀌는 흐름',
      'Customer Experience Journey',
      '고객경험 영역 데이터',
      'Development Experience Journey',
      'Apps · AI · Projects',
      '제때개발과 품질 개선',
      '빠른 의사결정과 품질무결성을 바탕으로 필요한 순간에 필요한 기능을 제공합니다.',
    ],
    name: 'About DEJ pipeline',
    reactSelector:
      "xpath=//*[normalize-space()='CEJ 데이터가 DEJ 실행으로 바뀌는 흐름']/ancestor::*[.//*[normalize-space()='Customer Experience Journey'] and .//*[normalize-space()='제때개발과 품질 개선']][1]",
    referenceFile: aboutDejReferenceFile,
    referenceSelector: '#pipeline',
    referenceUrl: toReferenceUrl(aboutDejReferenceFile),
    route: '/docs/about-dej',
    slug: 'about-dej-pipeline',
    trackerRow: 'About DEJ :: Pipeline',
  },
  {
    expectedReactText: [
      'History',
      'DEJ 콘셉트의 변화',
      '고객경험 여정에서 출발',
      'DEJ Portal 인트로로 철학을 시각화',
      'AX Studio 안의 실행형 경험으로 통합',
      '신속한 탐지와 제때개발로 환류',
    ],
    expectedReferenceText: [
      'History',
      'DEJ 콘셉트의 변화',
      '고객경험 여정에서 출발',
      'DEJ Portal 인트로로 철학을 시각화',
      'AX Studio 안의 실행형 경험으로 통합',
      '신속한 탐지와 제때개발로 환류',
    ],
    name: 'About DEJ timeline',
    reactSelector:
      "xpath=//*[normalize-space()='DEJ 콘셉트의 변화']/ancestor::*[.//*[normalize-space()='고객경험 여정에서 출발'] and .//*[normalize-space()='신속한 탐지와 제때개발로 환류']][1]",
    referenceFile: aboutDejReferenceFile,
    referenceSelector: "xpath=//*[@id='history']/div[1]",
    referenceUrl: toReferenceUrl(aboutDejReferenceFile),
    route: '/docs/about-dej',
    slug: 'about-dej-timeline',
    trackerRow: 'About DEJ :: Timeline',
  },
  {
    expectedReactText: [
      'Core Ideas',
      '포털 인트로의 키워드는 3C 2S 데이터와 Core Value 흐름으로 압축해 남깁니다.',
      'Connectivity',
      'Customization',
      'Care',
      'Servitization',
      'Sustainability',
      'Core Value',
      '신속한 탐지, 빠른 의사결정, 품질무결성, 제때개발, 구성원만족도',
    ],
    expectedReferenceText: [
      'Core Ideas',
      '포털 인트로의 키워드는 3C 2S 데이터와 Core Value 흐름으로 압축해 남깁니다.',
      'Connectivity',
      'Customization',
      'Care',
      'Servitization',
      'Sustainability',
      'Core Value',
      '신속한 탐지, 빠른 의사결정, 품질무결성, 제때개발, 구성원만족도',
    ],
    name: 'About DEJ core ideas',
    reactSelector:
      "xpath=//*[normalize-space()='Core Ideas']/ancestor::*[.//*[normalize-space()='Connectivity'] and .//*[normalize-space()='Core Value']][1]",
    referenceFile: aboutDejReferenceFile,
    referenceSelector:
      "xpath=//*[@id='history']//section[contains(@class,'card')][.//*[contains(normalize-space(),'Core Ideas')]]",
    referenceUrl: toReferenceUrl(aboutDejReferenceFile),
    route: '/docs/about-dej',
    slug: 'about-dej-core-ideas',
    trackerRow: 'About DEJ :: Core ideas',
  },
  {
    expectedReactText: [
      'Continue in AX Studio',
      'DEJ는 소개에서 끝나지 않고 AX Studio의 실제 기능으로 이어집니다.',
      'App Gallery',
      'AI Gallery',
      'Project / Publish',
      '지원 챗봇',
    ],
    expectedReferenceText: [
      'Continue in AX Studio',
      'DEJ는 소개에서 끝나지 않고 AX Studio의 실제 기능으로 이어집니다.',
      'App Gallery',
      'AI Gallery',
      'Project / Publish',
      '지원 챗봇',
    ],
    name: 'About DEJ continue CTA',
    reactSelector:
      "xpath=//*[normalize-space()='Continue in AX Studio']/ancestor::*[.//*[normalize-space()='App Gallery'] and .//*[normalize-space()='지원 챗봇']][1]",
    referenceFile: aboutDejReferenceFile,
    referenceSelector:
      "xpath=//*[@id='history']//section[contains(@class,'card')][.//*[contains(normalize-space(),'Continue in AX Studio')]]",
    referenceUrl: toReferenceUrl(aboutDejReferenceFile),
    route: '/docs/about-dej',
    slug: 'about-dej-continue-cta',
    trackerRow: 'About DEJ :: Continue CTA',
  },
  {
    expectedReactText: ['AX Studio', 'AI'],
    expectedReferenceText: ['AX Studio', 'AI', 'TN'],
    name: 'Shared App Shell topbar brand/layout',
    reactSelector: '[data-ref="app-header"]',
    referenceFile: launchpadReferenceFile,
    referenceSelector: '.topbar',
    referenceUrl: toReferenceUrl(launchpadReferenceFile),
    route: '/',
    slug: 'shared-shell-topbar',
    trackerRow: 'Shared App Shell :: Topbar brand/layout',
  },
  {
    expectedReactText: [
      'Store',
      'App Gallery',
      'AI Gallery',
      'Accessibility',
      'Domain',
      'Permission',
      'Storage',
      'Database',
      'Buckets',
      'Development',
      'Consoles',
      'Project/Publish',
      'Jupyter',
      'AI',
      'Workflow',
      'Chatbot',
      'Tool Inventory',
      'Keycenter',
      'Support',
      '다큐먼트',
      'About DEJ',
      '챗봇',
      '요청하기',
    ],
    expectedReferenceText: [
      'Store',
      'App Gallery',
      'AI Gallery',
      'Accessibility',
      'Domain',
      'Permission',
      'Storage',
      'Database',
      'Buckets',
      'Development',
      'Consoles',
      'Project/Publish',
      'Jupyter',
      'AI',
      'Workflow',
      'Chatbot',
      'Tool Inventory',
      'Keycenter',
      'Support',
      '다큐먼트',
      'About DEJ',
      '챗봇',
      '요청하기',
    ],
    name: 'Shared App Shell service menu',
    reactActions: ['open-service-menu'],
    reactSelector: '[data-ref="service-menu-panel"]',
    referenceActions: ['open-service-menu'],
    referenceFile: launchpadReferenceFile,
    referenceSelector: '.service-popover',
    referenceUrl: toReferenceUrl(launchpadReferenceFile),
    route: '/',
    slug: 'shared-shell-service-menu',
    trackerRow: 'Shared App Shell :: Service menu',
  },
  {
    expectedReactText: ['DEJ SYSTEMS', 'DEJ 챗봇', 'HEANS', 'HEVPDS'],
    expectedReactLinks: [
      {
        href: 'https://dej-chatbot.apps.hedej.lge.com',
        label: 'DEJ 챗봇',
        rel: 'noopener noreferrer',
        target: '_blank',
      },
      {
        href: 'https://workspace.hedej.lge.com/heans',
        label: 'HEANS',
        rel: 'noopener noreferrer',
        target: '_blank',
      },
      {
        href: 'https://workspace.hedej.lge.com/hevpds',
        label: 'HEVPDS',
        rel: 'noopener noreferrer',
        target: '_blank',
      },
    ],
    expectedReferenceText: ['DEJ 시스템', 'DEJ 챗봇', 'HEANS', 'HEVPDS'],
    expectedReferenceLinks: [
      {
        href: 'https://dej-chatbot.apps.hedej.lge.com',
        label: 'DEJ 챗봇',
        rel: 'noopener noreferrer',
        target: '_blank',
      },
      {
        href: 'https://workspace.hedej.lge.com/heans',
        label: 'HEANS',
        rel: 'noopener noreferrer',
        target: '_blank',
      },
      {
        href: 'https://workspace.hedej.lge.com/hevpds',
        label: 'HEVPDS',
        rel: 'noopener noreferrer',
        target: '_blank',
      },
    ],
    name: 'Shared App Shell external service links',
    reactActions: ['open-service-menu'],
    reactSelector: '[data-ref="external-service-links"]',
    referenceActions: ['open-service-menu'],
    referenceFile: launchpadReferenceFile,
    referenceSelector: '.service-outlinks',
    referenceUrl: toReferenceUrl(launchpadReferenceFile),
    route: '/',
    slug: 'shared-shell-external-links',
    trackerRow: 'Shared App Shell :: External service links',
  },
  {
    expectedReactText: [
      'Notifications',
      'Latest workspace activity',
      '523 total',
      '[Request] gfg Agent Creation',
      'Denied',
      'Outgoing',
    ],
    expectedReferenceText: ['notifications_none'],
    name: 'Shared App Shell notifications',
    reactActions: ['open-notifications'],
    reactSelector: '[data-ref="header-notifications-popover"]',
    referenceFile: launchpadReferenceFile,
    referenceSelector: '.tb-icon',
    referenceUrl: toReferenceUrl(launchpadReferenceFile),
    route: '/',
    slug: 'shared-shell-notifications',
    trackerRow: 'Shared App Shell :: Notifications',
  },
  {
    expectedReactText: [],
    expectedReactLinks: [
      {
        href: '/workspace/settings',
        label: 'Open Account Settings',
      },
    ],
    expectedReferenceText: ['TN'],
    expectedReferenceLinks: [
      {
        href: 'workspace_settings.html',
        label: '설정 페이지 열기',
      },
    ],
    name: 'Shared App Shell current user/avatar',
    reactSelector: '[data-ref="current-user-avatar"]',
    referenceFile: launchpadReferenceFile,
    referenceSelector: '.avatar',
    referenceUrl: toReferenceUrl(launchpadReferenceFile),
    route: '/',
    slug: 'shared-shell-current-user-avatar',
    trackerRow: 'Shared App Shell :: Current user/avatar',
  },
  {
    expectedReactText: [
      'Lethanh Nguyen 님, 반갑습니다 👋',
      '읽지 않은 알림 390건을 먼저 확인해 보세요.',
      '16 / 73',
      '전체 Workspace',
      '56',
      '전체 사용자',
      '₩3.3M',
      '누적 절감 비용',
      '161.9M',
      '월간 LLM 토큰',
    ],
    expectedReactRequests: ['GET /api/v2/launchpad/overview', 'GET /api/v2/launchpad/my-work'],
    expectedReferenceText: [
      'Lethanh Nguyen 님, 반갑습니다 👋',
      '읽지 않은 알림 390건을 먼저 확인해 보세요.',
      '16 / 73',
      '전체 Workspace',
      '56',
      '전체 사용자',
      '₩3.3M',
      '누적 절감 비용',
      '161.9M',
      '월간 LLM 토큰',
    ],
    expectedReferenceRequests: ['GET /api/v2/launchpad/overview', 'GET /api/v2/launchpad/my-work'],
    name: 'Launchpad personalized hero/header',
    reactSelector: '[data-ref="launchpad-hero"]',
    referenceFile: launchpadReferenceFile,
    referenceSelector: '.hero',
    referenceUrl: toReferenceUrl(launchpadReferenceFile),
    route: '/',
    slug: 'launchpad-hero',
    trackerRow: 'Launchpad :: Personalized hero/header',
  },
  {
    expectedReactText: [
      'Lethanh Nguyen 님, 반갑습니다 👋',
      '읽지 않은 알림 390건을 먼저 확인해 보세요.',
      '16 / 73',
      '전체 Workspace',
      'AX Studio Open',
      'AX Studio가 새롭게 오픈했습니다',
      'AX Studio 보기',
      '온라인 강의를 수강해 보세요',
      '사용자 경험 조사에 참여해 주세요',
      '아티클',
      'MCP를 활용한 개발 워크플로우 자동화',
      '운영 환경 토큰 관리 체크리스트',
      '가이드',
      '처음 시작하기',
      '프로젝트 생성 가이드',
      'Gallery',
      'DEJ App Gallery',
      'nova-1',
      '팀 공용 진입점으로 보기 좋은 앱',
      'sirius-ide-sample',
      'DEJ AI Gallery',
      'jean',
      'AI Gallery Preview',
      '내 알림',
      'app-gallery-install',
      '[Request] gfg Agent Creation',
      '내 배포 앱',
      '내 프로젝트',
      '0 / 524',
      'sasasasasa',
      '내 리소스',
      '전체 리소스',
      '160',
      'yg-nova-test-last',
      'aas',
    ],
    expectedReactRequests: [
      'GET /api/v2/launchpad/overview',
      'GET /api/v2/launchpad/my-work',
      'GET /api/v2/launchpad/resources',
    ],
    expectedReferenceText: [
      'Lethanh Nguyen 님, 반갑습니다 👋',
      '읽지 않은 알림 390건을 먼저 확인해 보세요.',
      '16 / 73',
      '전체 Workspace',
      'AX Studio Open',
      'AX Studio가 새롭게 오픈했습니다',
      'AX Studio 보기',
      '온라인 강의를 수강해 보세요',
      '사용자 경험 조사에 참여해 주세요',
      '아티클',
      'MCP를 활용한 개발 워크플로우 자동화',
      '운영 환경 토큰 관리 체크리스트',
      '가이드',
      '처음 시작하기',
      '프로젝트 생성 가이드',
      'Gallery',
      'DEJ App Gallery',
      'nova-1',
      '팀 공용 진입점으로 보기 좋은 앱',
      'sirius-ide-sample',
      'DEJ AI Gallery',
      'jean',
      'AI Gallery Preview',
      '내 알림',
      'app-gallery-install',
      '[Request] gfg Agent Creation',
      '내 배포 앱',
      '내 프로젝트',
      '0 / 524',
      'sasasasasa',
      '내 리소스',
      '전체 리소스',
      '160',
      'yg-nova-test-last',
      'aas',
    ],
    expectedReferenceRequests: [
      'GET /api/v2/launchpad/overview',
      'GET /api/v2/launchpad/my-work',
      'GET /api/v2/launchpad/resources',
    ],
    name: 'Launchpad full page',
    reactSelector: 'main',
    referenceFile: launchpadReferenceFile,
    referenceSelector: '.page',
    referenceUrl: toReferenceUrl(launchpadReferenceFile),
    route: '/',
    slug: 'launchpad-full-page',
    trackerRow: 'Launchpad :: Full page',
  },
  {
    expectedReactText: [
      'DEJ App Gallery',
      'App Gallery',
      '지금 배포 중인 앱을 기준으로, 용도에 맞는 추천 앱을 큐레이션해서 보여드립니다.',
      'Recommended Apps 11',
      'Published Apps 11',
      'Target Projects 72',
      'Categories 4',
      '조회 결과 11',
      '실데이터 하이라이트',
      '지금 추천하는 앱',
      'sirius-ide-sample',
      'sirius-test-uv27',
      'sirius-streamlit-python-lock',
      '함께 보는 AI 큐레이션',
      'Release Review Agent',
      'Workspace Helper Pack',
      'Insight Analyst Agent',
      'Recommended Highlights',
      '바로 써보기 좋은 개발 앱',
      '전체 (11)',
      'Development (11)',
      'Workspace (0)',
      'Operations (0)',
      'Analytics (0)',
      'Recommended Apps',
      'sirius-securitytest',
      'readonly-dev1',
      'tesss',
      'Collections',
      '목적에 따라 다시 묶어본 추천 앱',
      '지금 먼저 볼 앱',
      '카테고리별 추천 앱',
      '3 Apps',
      '1 Picks',
      '추천 앱 목록',
      '이번 페이지에서 눈에 띄는 흐름',
      '11 apps',
      '0 apps',
    ],
    expectedReactRequests: [
      'GET /api/v2/app-gallery/hero',
      'GET /api/v2/app-gallery/categories',
      'GET /api/v2/app-gallery/featured',
      'GET /api/v2/app-gallery/related-ai',
      'GET /api/v2/app-gallery/apps',
    ],
    expectedReferenceText: [
      'DEJ App Gallery',
      'App Gallery',
      '지금 배포 중인 앱을 기준으로, 용도에 맞는 추천 앱을 큐레이션해서 보여드립니다.',
      'Recommended Apps 11',
      'Published Apps 11',
      'Target Projects 72',
      'Categories 4',
      '조회 결과 11',
      '실데이터 하이라이트',
      '지금 추천하는 앱',
      'sirius-ide-sample',
      'sirius-test-uv27',
      'sirius-streamlit-python-lock',
      '함께 보는 AI 큐레이션',
      'Release Review Agent',
      'Workspace Helper Pack',
      'Insight Analyst Agent',
      'Recommended Highlights',
      '바로 써보기 좋은 개발 앱',
      '전체 (11)',
      'Development (11)',
      'Workspace (0)',
      'Operations (0)',
      'Analytics (0)',
      'Recommended Apps',
      'sirius-securitytest',
      'readonly-dev1',
      'tesss',
      'Collections',
      '목적에 따라 다시 묶어본 추천 앱',
      '지금 먼저 볼 앱',
      '카테고리별 추천 앱',
      '3 Apps',
      '1 Picks',
      '추천 앱 목록',
      '이번 페이지에서 눈에 띄는 흐름',
      '11 apps',
      '0 apps',
    ],
    expectedReferenceRequests: [
      'GET /api/v2/app-gallery/hero',
      'GET /api/v2/app-gallery/categories',
      'GET /api/v2/app-gallery/featured',
      'GET /api/v2/app-gallery/related-ai',
      'GET /api/v2/app-gallery/apps',
    ],
    name: 'App Gallery whole page',
    reactSelector: 'main',
    referenceFile: appGalleryReferenceFile,
    referenceSelector: '.page',
    referenceUrl: toReferenceUrl(appGalleryReferenceFile),
    route: '/workspace/app-gallery',
    slug: 'app-gallery-whole-page',
    trackerRow: 'App Gallery :: Whole page',
  },
  {
    expectedReactText: [
      'DEJ App Gallery',
      'App Gallery',
      '지금 배포 중인 앱을 기준으로, 용도에 맞는 추천 앱을 큐레이션해서 보여드립니다.',
      'Recommended Apps 11',
      'Published Apps 11',
      'Target Projects 72',
      'Categories 4',
      '조회 결과 11',
    ],
    expectedReferenceText: [
      'DEJ App Gallery',
      'App Gallery',
      '지금 배포 중인 앱을 기준으로, 용도에 맞는 추천 앱을 큐레이션해서 보여드립니다.',
      'Recommended Apps 11',
      'Published Apps 11',
      'Target Projects 72',
      'Categories 4',
      '조회 결과 11',
    ],
    name: 'App Gallery page head / intro',
    reactSelector:
      "xpath=//*[normalize-space()='DEJ App Gallery']/ancestor::*[contains(@class,'MuiStack-root')][1]",
    referenceFile: appGalleryReferenceFile,
    referenceSelector: '.page-head',
    referenceUrl: toReferenceUrl(appGalleryReferenceFile),
    route: '/workspace/app-gallery',
    slug: 'app-gallery-page-head-intro',
    trackerRow: 'App Gallery :: Page head / intro',
  },
  {
    expectedReactText: [
      '실데이터 하이라이트',
      '지금 추천하는 앱',
      '배포된 앱 중 먼저 살펴보면 좋은 앱을 보여드립니다.',
      'sirius-ide-sample',
      '배포 중',
      'sirius-test-uv27',
      'Development',
      'sirius-streamlit-python-lock',
      '함께 보는 AI 큐레이션',
      '함께 보면 좋은 AI',
      '추천 앱과 함께 이어서 볼 만한 AI 항목을 보여드립니다.',
      'Release Review Agent',
      'Workspace Helper Pack',
      'Insight Analyst Agent',
    ],
    expectedReferenceText: [
      '실데이터 하이라이트',
      '지금 추천하는 앱',
      '배포된 앱 중 먼저 살펴보면 좋은 앱을 보여드립니다.',
      'sirius-ide-sample',
      '배포 중',
      'sirius-test-uv27',
      'Development',
      'sirius-streamlit-python-lock',
      '함께 보는 AI 큐레이션',
      '함께 보면 좋은 AI',
      '추천 앱과 함께 이어서 볼 만한 AI 항목을 보여드립니다.',
      'Release Review Agent',
      'Workspace Helper Pack',
      'Insight Analyst Agent',
    ],
    name: 'App Gallery hero rail',
    reactSelector:
      "xpath=(//*[contains(normalize-space(),'실데이터 하이라이트')]/ancestor::*[contains(normalize-space(),'함께 보는 AI 큐레이션')])[last()]",
    referenceFile: appGalleryReferenceFile,
    referenceSelector: '.hero-rail',
    referenceUrl: toReferenceUrl(appGalleryReferenceFile),
    route: '/workspace/app-gallery',
    slug: 'app-gallery-hero-rail',
    trackerRow: 'App Gallery :: Hero rail',
  },
  {
    expectedReactText: [
      'Recommended Highlights',
      'Development',
      'sirius-ide-sample',
      '개발과 실행 흐름을 바로 이어가기 좋은 배포 앱입니다.',
      '프로젝트 작업을 바로 시작하거나 수정 흐름을 이어가기 좋습니다.',
      'static',
      'certificationValidation',
      '바로 써보기 좋은 개발 앱',
      '상세 보기',
      '추가 추천',
      'sirius-test-uv27',
      '함께 보기',
      'sirius-streamlit-python-lock',
    ],
    expectedReactDetailText: [
      'APP DETAIL',
      'sirius-ide-sample',
      '배포된 개발 앱',
      '설명',
      '개발과 실행 흐름을 바로 이어가기 좋은 배포 앱입니다. 프로젝트 허브에서 배포 정보와 연결 상태를 이어서 확인할 수 있습니다.',
      '연결 정보',
      'Projects Hub에서 확인',
      'sirius-ide-sample의 세부 배포 흐름과 연결 정보는 Projects Hub에서 이어서 볼 수 있습니다.',
      '핵심 포인트',
      '활용 케이스',
      '신규 기능 데모',
      '사전 조건',
      '배포된 프로젝트 접근 권한',
      '관련 AI 큐레이션',
      'Release Review Agent',
      'Workspace Helper Pack',
      '닫기',
    ],
    expectedReactRequests: [
      'GET /api/v2/app-gallery/featured',
      'GET /api/v2/app-gallery/apps/69e98728161e5a9910c7d52b',
    ],
    expectedReferenceText: [
      'Recommended Highlights',
      'Development',
      'sirius-ide-sample',
      '개발과 실행 흐름을 바로 이어가기 좋은 배포 앱입니다.',
      '프로젝트 작업을 바로 시작하거나 수정 흐름을 이어가기 좋습니다.',
      'static',
      'certificationValidation',
      '바로 써보기 좋은 개발 앱',
      '상세 보기',
      '추가 추천',
      'sirius-test-uv27',
      '함께 보기',
      'sirius-streamlit-python-lock',
    ],
    expectedReferenceDetailText: [
      'App Detail',
      'sirius-ide-sample',
      '배포된 개발 앱',
      '설명',
      '개발과 실행 흐름을 바로 이어가기 좋은 배포 앱입니다. 프로젝트 허브에서 배포 정보와 연결 상태를 이어서 확인할 수 있습니다.',
      '연결 정보',
      'Projects Hub에서 확인',
      'sirius-ide-sample의 세부 배포 흐름과 연결 정보는 Projects Hub에서 이어서 볼 수 있습니다.',
      '핵심 포인트',
      '활용 케이스',
      '신규 기능 데모',
      '사전 조건',
      '배포된 프로젝트 접근 권한',
      '관련 AI 큐레이션',
      'Release Review Agent',
      'Workspace Helper Pack',
    ],
    expectedReferenceRequests: [
      'GET /api/v2/app-gallery/featured',
      'GET /api/v2/app-gallery/apps/69e98728161e5a9910c7d52b',
    ],
    name: 'App Gallery curated highlights',
    reactDetailActions: ['open-app-gallery-featured-detail'],
    reactDetailSelector: '[role="dialog"]',
    reactSelector:
      "xpath=//*[normalize-space()='Recommended Highlights']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceDetailActions: ['open-app-gallery-featured-detail'],
    referenceDetailSelector: '#appDetailDialog',
    referenceFile: appGalleryReferenceFile,
    referenceSelector:
      "xpath=//*[@data-featured-main]/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(appGalleryReferenceFile),
    route: '/workspace/app-gallery',
    slug: 'app-gallery-curated-highlights',
    trackerRow: 'App Gallery :: Curated highlights',
  },
  {
    expectedReactAttributes: [
      {
        attribute: 'aria-pressed',
        label: 'default all category tab active state',
        selector: 'button:has-text("전체 (11)")',
        value: 'true',
      },
      {
        attribute: 'aria-pressed',
        label: 'development category tab inactive state',
        selector: 'button:has-text("Development (11)")',
        value: 'false',
      },
    ],
    expectedReactText: [
      '전체 (11)',
      'Development (11)',
      'Workspace (0)',
      'Operations (0)',
      'Analytics (0)',
    ],
    expectedReactRequests: ['GET /api/v2/app-gallery/categories'],
    expectedReferenceAttributes: [
      {
        attribute: 'aria-selected',
        label: 'default all category tab active state',
        selector: '[data-category-tab="all"]',
        value: 'true',
      },
      {
        attribute: 'aria-selected',
        label: 'development category tab inactive state',
        selector: '[data-category-tab="development"]',
        value: 'false',
      },
    ],
    expectedReferenceText: [
      '전체 (11)',
      'Development (11)',
      'Workspace (0)',
      'Operations (0)',
      'Analytics (0)',
    ],
    expectedReferenceRequests: ['GET /api/v2/app-gallery/categories'],
    name: 'App Gallery category tabs',
    reactSelector: '[aria-label="App categories"]',
    referenceFile: appGalleryReferenceFile,
    referenceSelector: '[data-category-tabs]',
    referenceUrl: toReferenceUrl(appGalleryReferenceFile),
    route: '/workspace/app-gallery',
    slug: 'app-gallery-category-tabs',
    trackerRow: 'App Gallery :: Category tabs',
  },
  {
    expectedReactText: [
      'Recommended Apps',
      '추천된 배포 앱을 확인해 보세요',
      '카테고리와 검색 조건에 맞는 앱을 골라 살펴보세요.',
      'sirius-ide-sample',
      '배포된 개발 앱',
      '개발과 실행 흐름을 바로 이어가기 좋은 배포 앱입니다.',
      'Development',
      'sirius-test-uv27',
      'sirius-streamlit-python-lock',
      'sirius-securitytest',
      'readonly-dev1',
      'tesss',
      '배포 중',
      '상세 보기',
    ],
    expectedReactDetailText: [
      'APP DETAIL',
      'sirius-ide-sample',
      '배포된 개발 앱',
      '설명',
      '개발과 실행 흐름을 바로 이어가기 좋은 배포 앱입니다. 프로젝트 허브에서 배포 정보와 연결 상태를 이어서 확인할 수 있습니다.',
      '연결 정보',
      'Projects Hub에서 확인',
      'sirius-ide-sample의 세부 배포 흐름과 연결 정보는 Projects Hub에서 이어서 볼 수 있습니다.',
      '핵심 포인트',
      '활용 케이스',
      '사전 조건',
      '관련 AI 큐레이션',
      'Release Review Agent',
      'Workspace Helper Pack',
      '닫기',
    ],
    expectedReactRequests: [
      'GET /api/v2/app-gallery/apps',
      'GET /api/v2/app-gallery/apps/69e98728161e5a9910c7d52b',
    ],
    expectedReferenceText: [
      'Recommended Apps',
      '추천된 배포 앱',
      '11개 앱을 찾았습니다. 원하는 항목을 골라 자세히 살펴보세요.',
      'sirius-ide-sample',
      '배포된 개발 앱',
      '개발과 실행 흐름을 바로 이어가기 좋은 배포 앱입니다.',
      'Development',
      'sirius-test-uv27',
      'sirius-streamlit-python-lock',
      'sirius-securitytest',
      'readonly-dev1',
      'tesss',
      '배포 중',
      '상세 보기',
    ],
    expectedReferenceDetailText: [
      'App Detail',
      'sirius-ide-sample',
      '배포된 개발 앱',
      '설명',
      '개발과 실행 흐름을 바로 이어가기 좋은 배포 앱입니다. 프로젝트 허브에서 배포 정보와 연결 상태를 이어서 확인할 수 있습니다.',
      '연결 정보',
      'Projects Hub에서 확인',
      'sirius-ide-sample의 세부 배포 흐름과 연결 정보는 Projects Hub에서 이어서 볼 수 있습니다.',
      '핵심 포인트',
      '활용 케이스',
      '사전 조건',
      '관련 AI 큐레이션',
      'Release Review Agent',
      'Workspace Helper Pack',
    ],
    expectedReferenceRequests: [
      'GET /api/v2/app-gallery/apps',
      'GET /api/v2/app-gallery/apps/69e98728161e5a9910c7d52b',
    ],
    name: 'App Gallery registered app cards',
    reactDetailActions: ['open-app-gallery-registered-detail'],
    reactDetailSelector: '[role="dialog"]',
    reactSelector:
      "xpath=//*[normalize-space()='Recommended Apps']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceDetailActions: ['open-app-gallery-registered-detail'],
    referenceDetailSelector: '#appDetailDialog',
    referenceFile: appGalleryReferenceFile,
    referenceSelector: "xpath=//*[@data-app-grid]/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(appGalleryReferenceFile),
    route: '/workspace/app-gallery',
    slug: 'app-gallery-registered-app-cards',
    trackerRow: 'App Gallery :: Registered app cards',
  },
  {
    expectedReactText: [
      'Collections',
      '목적에 따라 다시 묶어본 추천 앱',
      '추천 앱을 추천 흐름에 맞춰 다시 묶어 보여드립니다.',
      '지금 먼저 볼 앱',
      '배포된 앱 중 먼저 살펴보면 좋은 앱을 모았습니다.',
      '3 Apps',
      'sirius-ide-sample',
      '개발과 실행 흐름을 바로 이어가기 좋은 배포 앱입니다.',
      'Development',
      'sirius-test-uv27',
      'sirius-streamlit-python-lock',
      '카테고리별 추천 앱',
      '각 카테고리에서 가장 먼저 볼 만한 앱을 골라 비교할 수 있게 묶었습니다.',
      '1 Picks',
    ],
    expectedReactDetailText: [
      'APP DETAIL',
      'sirius-ide-sample',
      '연결 정보',
      'Projects Hub에서 확인',
      '관련 AI 큐레이션',
      'Release Review Agent',
      '닫기',
    ],
    expectedReactRequests: [
      'GET /api/v2/app-gallery/categories',
      'GET /api/v2/app-gallery/featured',
      'GET /api/v2/app-gallery/apps',
      'GET /api/v2/app-gallery/related-ai',
      'GET /api/v2/app-gallery/apps/69e98728161e5a9910c7d52b',
    ],
    expectedReferenceText: [
      'Collections',
      '목적에 따라 다시 묶어본 추천 앱',
      '추천 앱을 추천 흐름에 맞춰 다시 묶어 보여드립니다.',
      '지금 먼저 볼 앱',
      '배포된 앱 중 먼저 살펴보면 좋은 앱을 모았습니다.',
      '3 Apps',
      'sirius-ide-sample',
      '개발과 실행 흐름을 바로 이어가기 좋은 배포 앱입니다.',
      'Development',
      'sirius-test-uv27',
      'sirius-streamlit-python-lock',
      '카테고리별 추천 앱',
      '각 카테고리에서 먼저 볼 만한 앱을 골라 비교할 수 있게 묶었습니다.',
      '1 Picks',
    ],
    expectedReferenceDetailText: [
      'App Detail',
      'sirius-ide-sample',
      '연결 정보',
      'Projects Hub에서 확인',
      '관련 AI 큐레이션',
      'Release Review Agent',
    ],
    expectedReferenceRequests: [
      'GET /api/v2/app-gallery/categories',
      'GET /api/v2/app-gallery/featured',
      'GET /api/v2/app-gallery/apps',
      'GET /api/v2/app-gallery/related-ai',
      'GET /api/v2/app-gallery/apps/69e98728161e5a9910c7d52b',
    ],
    name: 'App Gallery collections',
    reactDetailActions: ['open-app-gallery-collection-detail'],
    reactDetailSelector: '[role="dialog"]',
    reactSelector:
      "xpath=//*[normalize-space()='Collections']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceDetailActions: ['open-app-gallery-collection-detail'],
    referenceDetailSelector: '#appDetailDialog',
    referenceFile: appGalleryReferenceFile,
    referenceSelector:
      "xpath=//*[contains(normalize-space(),'Collections')]/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(appGalleryReferenceFile),
    route: '/workspace/app-gallery',
    slug: 'app-gallery-collections',
    trackerRow: 'App Gallery :: Collections',
  },
  {
    expectedReactText: [
      '추천 앱 목록',
      'sirius-ide-sample',
      '배포된 개발 앱',
      'sirius-test-uv27',
      'sirius-streamlit-python-lock',
      '이번 페이지에서 눈에 띄는 흐름',
      'Development',
      '프로젝트 생성과 IDE 진입을 빠르게 연결하는 앱',
      '11 apps',
      'Workspace',
      '협업, 문서, 포털 성격의 운영 앱',
      '0 apps',
      'Operations',
      '배포와 상태 점검, 운영 자동화 흐름',
    ],
    expectedReactRequests: [
      'GET /api/v2/app-gallery/categories',
      'GET /api/v2/app-gallery/featured',
      'GET /api/v2/app-gallery/apps',
    ],
    expectedReferenceText: [
      '추천 앱 목록',
      'sirius-ide-sample',
      '배포된 개발 앱',
      'sirius-test-uv27',
      'sirius-streamlit-python-lock',
      '이번 페이지에서 눈에 띄는 흐름',
      'Development',
      '프로젝트 생성과 IDE 진입을 빠르게 연결하는 앱',
      '11 apps',
      'Workspace',
      '협업, 문서, 포털 성격의 운영 앱',
      '0 apps',
      'Operations',
      '배포와 상태 점검, 운영 자동화 흐름',
    ],
    expectedReferenceRequests: [
      'GET /api/v2/app-gallery/categories',
      'GET /api/v2/app-gallery/featured',
      'GET /api/v2/app-gallery/apps',
    ],
    name: 'App Gallery side rail summaries',
    reactSelector:
      "xpath=//*[normalize-space()='추천 카탈로그' or normalize-space()='추천 앱 목록']/ancestor::*[.//*[normalize-space()='이번 페이지에서 눈에 띄는 흐름']][1]",
    referenceFile: appGalleryReferenceFile,
    referenceSelector: '.side-col',
    referenceUrl: toReferenceUrl(appGalleryReferenceFile),
    route: '/workspace/app-gallery',
    slug: 'app-gallery-side-rail-summaries',
    trackerRow: 'App Gallery :: Side rail summaries',
  },
  {
    expectedReactText: [
      'Model',
      'agent별 모델 구성',
      'primary model과 runtime provider를 함께 보여줘 운영자가 연결 상태를 읽기 쉽게 합니다.',
      'jean',
      'Dify',
      'testdifyinagent',
      'Agent는 실행 흐름이 먼저 보이도록 둡니다',
      'entry channel보다 단계 수와 approval checkpoint를 우선 노출합니다.',
      'Key는 Keycenter에서 연결 상태만 확인합니다',
      'agent 화면에서는 secret이 아니라 어떤 key pool을 참조하는지만 보여줍니다.',
      '프로젝트 바인딩보다 운영 기준을 먼저 보여줍니다',
      'workflow 구조와 key tier가 비교 포인트가 되도록 유지합니다.',
      'Keycenter 보기',
    ],
    expectedReactLinks: [
      {
        href: '/workspace/keycenter',
        label: 'Keycenter 보기',
      },
    ],
    expectedReactRequests: [
      'GET /api/v2/agents/panels/models',
      'GET /api/v2/panels/tips?surface=agents',
    ],
    expectedReferenceText: [
      'Tips',
      'Agent 운영 팁',
      'Agent Hub는 챗봇 노출면보다 자동화 실행 주체를 다루므로 workflow와 key 정책이 먼저 읽혀야 합니다.',
      'Agent는 실행 흐름이 먼저 보이도록 둡니다',
      'entry channel보다 단계 수와 approval checkpoint를 우선 노출합니다.',
      'Key는 Keycenter에서 연결 상태만 확인합니다',
      'agent 화면에서는 secret이 아니라 어떤 key pool을 참조하는지만 보여줍니다.',
      '프로젝트 바인딩보다 운영 기준을 먼저 보여줍니다',
      'workflow 구조와 key tier가 비교 포인트가 되도록 유지합니다.',
      'Keycenter 보기',
    ],
    expectedReferenceLinks: [
      {
        href: '/workspace/keycenter',
        label: 'Keycenter 보기',
      },
    ],
    expectedReferenceRequests: [
      'GET /api/v2/agents/panels/models',
      'GET /api/v2/panels/tips?surface=agents',
    ],
    name: 'Workflow / Agent Hub agent modeling / tips',
    reactSelector:
      "xpath=//*[normalize-space()='agent별 모델 구성']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: agentHubReferenceFile,
    referenceSelector:
      "xpath=//*[contains(normalize-space(),'Tips') and contains(normalize-space(),'운영 팁')]/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(agentHubReferenceFile),
    route: '/workspace/agents',
    slug: 'agent-hub-modeling-tips',
    trackerRow: 'Workflow / Agent Hub :: Agent modeling / tips',
  },
  {
    expectedReactText: [
      'Guide Links',
      'Agent 연계 허브',
      '실행 주체 화면에서 credential 정책과 연결 허브로 자연스럽게 이동할 수 있게 구성합니다.',
      'Keycenter',
      'shared gateway key와 paid tier 정책을 확인합니다.',
      'Projects Hub',
      'agent가 연결된 프로젝트 맥락을 확인합니다.',
      'Tool Inventory',
      '외부 도구나 MCP 연결 구성을 확인합니다.',
      '런치패드로 돌아가기',
    ],
    expectedReactLinks: [
      {
        href: '/workspace/keycenter',
        label: 'Keycenter',
      },
      {
        href: '/workspace/projects',
        label: 'Projects Hub',
      },
      {
        href: '/workspace/tool-inventory',
        label: 'Tool Inventory',
      },
      {
        href: '/launchpad',
        label: '런치패드로 돌아가기',
      },
    ],
    expectedReactRequests: ['GET /api/v2/panels/guide-links?surface=agents'],
    expectedReferenceAttributes: [
      {
        attribute: 'href',
        label: 'reference Keycenter guide CTA',
        selector: '.hub-briefing-route:has-text("Keycenter") .hub-briefing-route-link',
        value: '/workspace/keycenter',
      },
      {
        attribute: 'href',
        label: 'reference Projects Hub guide CTA',
        selector: '.hub-briefing-route:has-text("Projects Hub") .hub-briefing-route-link',
        value: '/workspace/projects',
      },
      {
        attribute: 'href',
        label: 'reference Tool Inventory guide CTA',
        selector: '.hub-briefing-route:has-text("Tool Inventory") .hub-briefing-route-link',
        value: '/workspace/tool-inventory',
      },
    ],
    expectedReferenceText: [
      'Guide Links',
      'Agent 연계 허브',
      '실행 주체 화면에서 credential 정책과 연결 허브로 자연스럽게 이동할 수 있게 구성합니다.',
      'Keycenter',
      'shared gateway key와 paid tier 정책을 확인합니다.',
      'Projects Hub',
      'agent가 연결된 프로젝트 맥락을 확인합니다.',
      'Tool Inventory',
      '외부 도구나 MCP 연결 구성을 확인합니다.',
      '바로가기',
      '런치패드로 돌아가기',
    ],
    expectedReferenceLinks: [
      {
        href: '/launchpad',
        label: '런치패드로 돌아가기',
      },
    ],
    expectedReferenceRequests: ['GET /api/v2/panels/guide-links?surface=agents'],
    name: 'Workflow / Agent Hub guide links',
    reactSelector:
      "xpath=//*[normalize-space()='Agent 연계 허브']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: agentHubReferenceFile,
    referenceSelector:
      "xpath=//section[contains(@class,'panel')][contains(normalize-space(),'Guide Links') and contains(normalize-space(),'Keycenter')]",
    referenceUrl: toReferenceUrl(agentHubReferenceFile),
    route: '/workspace/agents',
    slug: 'agent-hub-guide-links',
    trackerRow: 'Workflow / Agent Hub :: Guide links',
  },
  {
    expectedReactText: [
      'Runtime Status',
      '현재 agent runtime 상태',
      '실행 중인 agent와 검토 중인 agent를 한 번에 확인합니다.',
      'Runtime rows',
      '2 agents',
      'jean',
      'Workflow · dify',
      'testdifyinagent',
      'Review',
    ],
    expectedReactRequests: ['GET /api/v2/agents/panels/runtime-status'],
    expectedReferenceText: [
      'Runtime Status',
      '현재 agent runtime 상태',
      '실행 중인 agent와 검토 중인 agent를 한 번에 확인합니다.',
      '0',
      '현재 모니터링 중인 리소스',
      'Healthy',
      'Needs Action',
      'Unknown',
      'jean',
      'Workflow · dify',
      'testdifyinagent',
      'Review',
    ],
    expectedReferenceRequests: ['GET /api/v2/agents/panels/runtime-status'],
    name: 'Workflow / Agent Hub runtime rail',
    reactSelector:
      "xpath=//*[normalize-space()='현재 agent runtime 상태']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: agentHubReferenceFile,
    referenceSelector:
      "xpath=//aside[contains(@class,'side-col')][contains(normalize-space(),'현재') and (contains(normalize-space(),'서비스 상태') or contains(normalize-space(),'agent runtime 상태'))]",
    referenceUrl: toReferenceUrl(agentHubReferenceFile),
    route: '/workspace/agents',
    slug: 'agent-hub-runtime-rail',
    trackerRow: 'Workflow / Agent Hub :: Runtime rail',
  },
  {
    expectedReactText: [
      'Tips',
      '버킷 운영 팁',
      '버킷 허브는 점유율과 노출 상태를 빠르게 판단하는 데 집중하고, 세부 운영 가이드는 패널로 분리합니다.',
      '퍼블릭 버킷은 노출 경로를 먼저 확인합니다',
      '도메인 연결 여부와 외부 공개 범위를 함께 읽어야 안전합니다.',
      '사용량 증가는 프로젝트 맥락과 같이 봅니다',
      '용량 급증은 연결된 프로젝트나 배포 이벤트와 함께 확인하는 편이 빠릅니다.',
      '아카이브 후보는 접근 패턴과 같이 판단합니다',
      '단순 용량만이 아니라 최근 사용 여부를 함께 보고 정리합니다.',
      '연결 프로젝트 보기',
    ],
    expectedReactLinks: [
      {
        href: '/workspace/projects',
        label: '연결 프로젝트 보기',
      },
    ],
    expectedReactRequests: ['GET /api/v2/panels/tips?surface=buckets'],
    expectedReferenceText: [
      'Tips',
      '버킷 운영 팁',
      '버킷 카드에서는 제어에 필요한 정보만 남기고, 참고할 내용은 아래 패널에서 짧게 확인하는 구조로 맞췄습니다.',
      '퍼블릭 버킷은 노출 경로를 먼저 확인합니다',
      '도메인 연결 여부와 외부 공개 범위를 함께 읽어야 안전합니다.',
      '사용량 증가는 프로젝트 맥락과 같이 봅니다',
      '용량 급증은 연결된 프로젝트나 배포 이벤트와 함께 확인하는 편이 빠릅니다.',
      '아카이브 후보는 접근 패턴과 같이 판단합니다',
      '단순 용량만이 아니라 최근 사용 여부를 함께 보고 정리합니다.',
      '연결 프로젝트 보기',
    ],
    expectedReferenceLinks: [
      {
        href: '/workspace/projects',
        label: '연결 프로젝트 보기',
      },
    ],
    expectedReferenceRequests: ['GET /api/v2/panels/tips?surface=buckets'],
    name: 'Bucket Hub bucket operation tips',
    reactSelector:
      "xpath=//*[normalize-space()='버킷 운영 팁']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: bucketHubReferenceFile,
    referenceSelector:
      "xpath=//*[normalize-space()='버킷 운영 팁']/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(bucketHubReferenceFile),
    route: '/workspace/buckets',
    slug: 'bucket-hub-operation-tips',
    trackerRow: 'Bucket Hub :: Bucket operation tips',
  },
  {
    expectedReactText: [
      'Guide Links',
      '스토리지 연계 허브',
      '버킷 사용 시 자주 이어지는 관련 허브 링크를 제공합니다.',
      'Projects Hub',
      '버킷이 연결된 프로젝트와 사용 맥락을 확인합니다.',
      'Domain Hub',
      '퍼블릭 버킷이 연결된 도메인 노출 경로를 확인합니다.',
      'Permission Hub',
      '공유 정책과 접근 범위를 점검합니다.',
      '런치패드로 돌아가기',
    ],
    expectedReactLinks: [
      {
        href: '/workspace/projects',
        label: 'Projects Hub',
      },
      {
        href: '/workspace/domains',
        label: 'Domain Hub',
      },
      {
        href: '/workspace/permissions',
        label: 'Permission Hub',
      },
      {
        href: '/launchpad',
        label: '런치패드로 돌아가기',
      },
    ],
    expectedReactRequests: ['GET /api/v2/panels/guide-links?surface=buckets'],
    expectedReferenceAttributes: [
      {
        attribute: 'href',
        label: 'reference Projects Hub guide CTA',
        selector: '.hub-briefing-route:has-text("Projects Hub") .hub-briefing-route-link',
        value: '/workspace/projects',
      },
      {
        attribute: 'href',
        label: 'reference Domain Hub guide CTA',
        selector: '.hub-briefing-route:has-text("Domain Hub") .hub-briefing-route-link',
        value: '/workspace/domains',
      },
      {
        attribute: 'href',
        label: 'reference Permission Hub guide CTA',
        selector: '.hub-briefing-route:has-text("Permission Hub") .hub-briefing-route-link',
        value: '/workspace/permissions',
      },
    ],
    expectedReferenceText: [
      'Guide Links',
      '가이드 링크',
      '운영 문서와 연관 허브 진입점은 카드 안에 넣지 않고, 링크 패널에서 분리해 여는 방식으로 정리했습니다.',
      'Projects Hub',
      '버킷이 연결된 프로젝트와 사용 맥락을 확인합니다.',
      'Domain Hub',
      '퍼블릭 버킷이 연결된 도메인 노출 경로를 확인합니다.',
      'Permission Hub',
      '공유 정책과 접근 범위를 점검합니다.',
      '바로가기',
      '런치패드로 돌아가기',
    ],
    expectedReferenceLinks: [
      {
        href: '/launchpad',
        label: '런치패드로 돌아가기',
      },
    ],
    expectedReferenceRequests: ['GET /api/v2/panels/guide-links?surface=buckets'],
    name: 'Bucket Hub guide links',
    reactSelector:
      "xpath=//*[normalize-space()='스토리지 연계 허브']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: bucketHubReferenceFile,
    referenceSelector:
      "xpath=//*[normalize-space()='가이드 링크']/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(bucketHubReferenceFile),
    route: '/workspace/buckets',
    slug: 'bucket-hub-guide-links',
    trackerRow: 'Bucket Hub :: Guide links',
  },
  {
    expectedReactText: [
      'Bucket Usage',
      '현재 주요 버킷 사용량',
      '우측 레일은 주요 버킷의 사용량과 점유율을 간단히 보여줍니다.',
      'Usage summary',
      '1.1 GiB / 59 TiB',
      'test-asd',
      '706 MiB used · 5 GiB quota',
      'milvus-bucket',
      '423 MiB used · 100 GiB quota',
      'sirius-bucket-relsw-yj',
      '111 KiB used · 1 GiB quota',
      'sirius-project3',
      '68 KiB used · 10 GiB quota',
      'ygbucket',
      '30 KiB used · 2 GiB quota',
      '14%',
      '0%',
    ],
    expectedReactLocatorText: [
      {
        label: 'React usage rail summary total',
        selector: "xpath=.//*[normalize-space()='Usage summary']/following-sibling::*[1]",
        text: '1.1 GiB / 59 TiB',
      },
    ],
    expectedReactRequests: ['GET /api/v2/buckets/panels/usage'],
    expectedReferenceText: [
      'Bucket Usage',
      '현재 주요 버킷 사용량',
      '버킷의 사용량과 점유율을 확인합니다.',
      '현재 모니터링 중인 리소스',
      'live snapshot',
      'Capacity Watch',
      'Bindings',
      'Freshness',
      'test-asd',
      '706MB used / 5.00GB quota',
      'milvus-bucket',
      '423MB used / 100GB quota',
      'sirius-bucket-relsw-yj',
      '111KB used / 1.00GB quota',
      'sirius-project3',
      '68.0KB used / 10.0GB quota',
      'ygbucket',
      '30.4KB used / 2.00GB quota',
      '14%',
      '0%',
    ],
    expectedReferenceLocatorText: [
      {
        label: 'reference usage rail monitored count',
        selector: '.hub-briefing-overview-value',
        text: '2',
      },
      {
        label: 'reference usage rail Capacity Watch count',
        selector:
          '.hub-briefing-overview-stat:has-text("Capacity Watch") .hub-briefing-overview-number',
        text: '2',
      },
      {
        label: 'reference usage rail Bindings count',
        selector: '.hub-briefing-overview-stat:has-text("Bindings") .hub-briefing-overview-number',
        text: '2',
      },
      {
        label: 'reference usage rail Freshness count',
        selector: '.hub-briefing-overview-stat:has-text("Freshness") .hub-briefing-overview-number',
        text: '2',
      },
    ],
    expectedReferenceRequests: ['GET /api/v2/buckets/panels/usage'],
    name: 'Bucket Hub usage rail',
    reactSelector:
      "xpath=//*[normalize-space()='Bucket Usage']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: bucketHubReferenceFile,
    referenceSelector:
      "xpath=//aside[contains(@class,'side-col')][contains(normalize-space(),'Bucket Usage') and contains(normalize-space(),'현재 주요 버킷 사용량')]",
    referenceUrl: toReferenceUrl(bucketHubReferenceFile),
    route: '/workspace/buckets',
    slug: 'bucket-hub-usage-rail',
    trackerRow: 'Bucket Hub :: Usage rail',
  },
  {
    expectedReactText: [
      'Accessibility · Domain Provisioning',
      'Domain Hub',
      '워크스페이스 DNS 리소스 모음입니다.',
      '새 도메인 생성',
      '프로젝트 허브 보기',
      '등록 도메인',
      '바인딩 프로젝트',
      '정상 인증서',
      '연결 완료',
      'Connected 3 · Pending 34',
      '37개 도메인 중 0개 연결',
      'Issued 0 · Review 30',
      'Ready 0 · None 30',
      'View',
      '전체',
      '대기',
      '검토',
      '인증서',
      'DNS Fleet',
      'Domains',
      '35개의 도메인 리소스를 실제 API 응답으로 렌더링합니다.',
      '8 loaded · 35 total',
      'hango-test.com',
      '인증서 발급 대기',
      '바인딩 전',
      'api/v2/domains',
      'DNS 운영 팁',
      '도메인은 단일 프로젝트 바인딩을 기본으로 봅니다',
      '도메인 연계 허브',
      'Projects Hub',
      'Certificate Status',
      '현재 인증서 상태',
      'Connection Status',
      '현재 커넥션 상태',
    ],
    expectedReactDetailText: [
      '도메인을 생성합니다',
      '이름만 입력하면 나머지 연결과 인증서 설정은 상세 화면에서 이어서 진행할 수 있습니다.',
      '도메인 이름',
      '아직 입력되지 않았습니다.',
      '도메인 이름을 입력해주세요.',
      '현재 화면에서는 이름만 먼저 등록하고, 이후 상세에서 프로젝트와 연결합니다.',
      '취소',
      '도메인 생성',
    ],
    expectedReactLinks: [
      {
        href: '/workspace/projects',
        label: '프로젝트 허브 보기',
      },
    ],
    expectedReactRequests: [
      'GET /api/v2/domains',
      'GET /api/v2/domains/stats',
      'GET /api/v2/domains/filters',
      'GET /api/v2/domains/panels/certificates',
      'GET /api/v2/domains/panels/connections',
      'GET /api/v2/domains/67b7f67ddefef46bea926e61/certificate',
      'GET /api/v2/domains/67b7f67ddefef46bea926e61/connection',
      'GET /api/v2/panels/tips?surface=domains',
      'GET /api/v2/panels/guide-links?surface=domains',
    ],
    expectedReferenceText: [
      'Accessibility · Domain Provisioning',
      'Domain Hub',
      '워크스페이스 DNS 리소스 모음입니다.',
      '새 도메인 생성',
      '프로젝트 허브 보기',
      '등록 도메인',
      '바인딩 프로젝트',
      '정상 인증서',
      '연결 완료',
      'View',
      '전체',
      '대기',
      '검토',
      '인증서',
      'DNS Fleet',
      'Domains',
      '35개의 도메인 리소스를 실제 API 응답으로 렌더링합니다.',
      'hango-test.com',
      'Custom DNS · None Route',
      '인증서 발급 대기',
      '바인딩 전',
      'api/v2/domains',
      'DNS 운영 팁',
      '도메인은 단일 프로젝트 바인딩을 기본으로 봅니다',
      '도메인 연계 허브',
      'Projects Hub',
      'Certificate Status',
      '현재 인증서 상태',
      'Connection Status',
      '현재 커넥션 상태',
    ],
    expectedReferenceDetailText: [
      '도메인을 생성합니다',
      '이름만 입력하면 나머지 연결과 인증서 설정은 상세 화면에서 이어서 진행할 수 있습니다.',
      '도메인 이름',
      '아직 입력되지 않았습니다.',
      '도메인 이름을 입력해주세요.',
      '현재 화면에서는 이름만 먼저 등록하고, 이후 상세에서 프로젝트와 연결합니다.',
      '취소',
      '도메인 생성',
    ],
    expectedReferenceLinks: [
      {
        href: 'workspace_projects_hub.html',
        label: '프로젝트 허브 보기',
      },
    ],
    expectedReferenceRequests: [
      'GET /api/v2/domains',
      'GET /api/v2/domains/stats',
      'GET /api/v2/domains/filters',
      'GET /api/v2/domains/panels/certificates',
      'GET /api/v2/domains/panels/connections',
      'GET /api/v2/domains/67b7f67ddefef46bea926e61/certificate',
      'GET /api/v2/domains/67b7f67ddefef46bea926e61/connection',
      'GET /api/v2/panels/tips?surface=domains',
      'GET /api/v2/panels/guide-links?surface=domains',
    ],
    name: 'Domain Hub full page',
    reactDetailActions: ['open-domain-create-dialog'],
    reactDetailSelector: '[role="dialog"]',
    reactSelector: 'main',
    referenceDetailActions: ['open-domain-create-dialog'],
    referenceDetailSelector: '#domainCreateModal',
    referenceFile: domainHubReferenceFile,
    referenceSelector: '.page',
    referenceUrl: toReferenceUrl(domainHubReferenceFile),
    route: '/workspace/domains',
    slug: 'domain-hub-full-page',
    timeout: 45_000,
    trackerRow: 'Domain Hub :: Full page',
  },
  {
    expectedReactText: [
      'Tips',
      'DNS 운영 팁',
      '도메인 카드는 연결 판단에 필요한 정보만 남기고, 절차성 안내는 보조 패널로 분리합니다.',
      '도메인은 단일 프로젝트 바인딩을 기본으로 봅니다',
      '같은 DNS 리소스에 여러 프로젝트를 섞지 않고 연결 관계를 명확하게 유지합니다.',
      '인증서와 연결 상태를 함께 봅니다',
      '오픈 전 인증서 발급 상태와 ingress 또는 CDN 연결 상태를 동시에 확인합니다.',
      '승인과 예외 절차는 카드 밖에서 다룹니다',
      '운영 절차는 가이드 링크로 분리해 카드가 복잡해지지 않게 유지합니다.',
      '연결 프로젝트 보기',
    ],
    expectedReactLinks: [
      {
        href: '/workspace/projects',
        label: '연결 프로젝트 보기',
      },
    ],
    expectedReactRequests: ['GET /api/v2/panels/tips?surface=domains'],
    expectedReferenceText: [
      'Tips',
      'DNS 운영 팁',
      '도메인 카드는 연결 판단에 필요한 정보만 남기고, 절차성 안내는 보조 패널로 분리합니다.',
      '도메인은 단일 프로젝트 바인딩을 기본으로 봅니다',
      '같은 DNS 리소스에 여러 프로젝트를 섞지 않고 연결 관계를 명확하게 유지합니다.',
      '인증서와 연결 상태를 함께 봅니다',
      '오픈 전 인증서 발급 상태와 ingress 또는 CDN 연결 상태를 동시에 확인합니다.',
      '승인과 예외 절차는 카드 밖에서 다룹니다',
      '운영 절차는 가이드 링크로 분리해 카드가 복잡해지지 않게 유지합니다.',
      '연결 프로젝트 보기',
    ],
    expectedReferenceLinks: [
      {
        href: '/workspace/projects',
        label: '연결 프로젝트 보기',
      },
    ],
    expectedReferenceRequests: ['GET /api/v2/panels/tips?surface=domains'],
    name: 'Domain Hub DNS operation tips',
    reactSelector:
      "xpath=//*[normalize-space()='DNS 운영 팁']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: domainHubReferenceFile,
    referenceSelector:
      "xpath=//*[normalize-space()='DNS 운영 팁']/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(domainHubReferenceFile),
    route: '/workspace/domains',
    slug: 'domain-hub-dns-operation-tips',
    trackerRow: 'Domain Hub :: DNS operation tips',
  },
  {
    expectedReactText: [
      'Guide Links',
      '도메인 연계 허브',
      '도메인 연결과 승인 흐름을 이어서 볼 수 있는 화면을 제공합니다.',
      'Projects Hub',
      '각 DNS 리소스가 어떤 프로젝트에 바인딩되는지 확인합니다.',
      'Permission Hub',
      '인증서 갱신 승인과 예외 처리 흐름을 확인합니다.',
      'Bucket Hub',
      '퍼블릭 버킷과 연결되는 노출 흐름을 함께 봅니다.',
      '런치패드로 돌아가기',
    ],
    expectedReactLinks: [
      {
        href: '/workspace/projects',
        label: 'Projects Hub',
      },
      {
        href: '/workspace/permissions',
        label: 'Permission Hub',
      },
      {
        href: '/workspace/buckets',
        label: 'Bucket Hub',
      },
      {
        href: '/launchpad',
        label: '런치패드로 돌아가기',
      },
    ],
    expectedReactRequests: ['GET /api/v2/panels/guide-links?surface=domains'],
    expectedReferenceAttributes: [
      {
        attribute: 'href',
        label: 'reference Projects Hub guide CTA',
        selector: '.hub-briefing-route:has-text("Projects Hub") .hub-briefing-route-link',
        value: '/workspace/projects',
      },
      {
        attribute: 'href',
        label: 'reference Permission Hub guide CTA',
        selector: '.hub-briefing-route:has-text("Permission Hub") .hub-briefing-route-link',
        value: '/workspace/permissions',
      },
      {
        attribute: 'href',
        label: 'reference Bucket Hub guide CTA',
        selector: '.hub-briefing-route:has-text("Bucket Hub") .hub-briefing-route-link',
        value: '/workspace/buckets',
      },
    ],
    expectedReferenceText: [
      'Guide Links',
      '도메인 연계 허브',
      '도메인 연결과 승인 흐름을 이어서 볼 수 있는 화면을 제공합니다.',
      'Projects Hub',
      '각 DNS 리소스가 어떤 프로젝트에 바인딩되는지 확인합니다.',
      'Permission Hub',
      '인증서 갱신 승인과 예외 처리 흐름을 확인합니다.',
      'Bucket Hub',
      '퍼블릭 버킷과 연결되는 노출 흐름을 함께 봅니다.',
      '바로가기',
      '런치패드로 돌아가기',
    ],
    expectedReferenceLinks: [
      {
        href: '/launchpad',
        label: '런치패드로 돌아가기',
      },
    ],
    expectedReferenceRequests: ['GET /api/v2/panels/guide-links?surface=domains'],
    name: 'Domain Hub guide links',
    reactSelector:
      "xpath=//*[normalize-space()='도메인 연계 허브']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: domainHubReferenceFile,
    referenceSelector:
      "xpath=//*[normalize-space()='도메인 연계 허브']/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(domainHubReferenceFile),
    route: '/workspace/domains',
    slug: 'domain-hub-guide-links',
    trackerRow: 'Domain Hub :: Guide links',
  },
  {
    expectedReactText: [
      'Accessibility · IAM & Approvals',
      'Permission Hub',
      'Permission Realm 모음입니다.',
      '새 Permission 생성',
      '프로젝트 목록',
      '등록 Realm',
      '배정 인원',
      '연결된 프로젝트',
      '요청 대기',
      'View',
      '전체',
      'Scoped',
      'Loaded 6 of 23 realms',
      'Permission Realms',
      'sasaas',
      'yg-permissions-test-a',
      'sirius',
      '권한 운영 팁',
      '승인은 리소스 영향 범위와 같이 봅니다',
      '권한 연계 허브',
      'Domain Hub',
      'Request List',
      '현재 요청 목록',
      'Request inbox contract needed',
      'GET /api/v2/permissions/requests response shape is missing.',
    ],
    expectedReactRequests: [
      'GET /api/v2/permissions/realms',
      'GET /api/v2/permissions/realms/stats',
      'GET /api/v2/permissions/realms/filters',
      'GET /api/v2/panels/tips?surface=permissions',
      'GET /api/v2/panels/guide-links?surface=permissions',
    ],
    expectedReferenceText: [
      'Accessibility · IAM & Approvals',
      'Permission Hub',
      'Permission Realm 모음입니다.',
      '새 Permission 생성',
      '프로젝트 목록',
      '등록 Realm',
      '배정 인원',
      '연결된 프로젝트',
      '요청 대기',
      'View',
      '전체',
      'Scoped',
      'Permission Realms',
      'sasaas',
      'yg-permissions-test-a',
      'sirius',
      '권한 운영 팁',
      '승인은 리소스 영향 범위와 같이 봅니다',
      '권한 연계 허브',
      '현재 요청 목록',
      '표시할 요청이 없습니다.',
    ],
    expectedReferenceRequests: [
      'GET /api/v2/permissions/realms',
      'GET /api/v2/permissions/realms/stats',
      'GET /api/v2/permissions/realms/filters',
      'GET /api/v2/permissions/requests',
      'GET /api/v2/panels/tips?surface=permissions',
      'GET /api/v2/panels/guide-links?surface=permissions',
    ],
    name: 'Permission Hub full page',
    reactSelector: 'main',
    referenceFile: permissionHubReferenceFile,
    referenceSelector: '.page',
    referenceUrl: toReferenceUrl(permissionHubReferenceFile),
    route: '/workspace/permissions',
    slug: 'permission-hub-full-page',
    trackerRow: 'Permission Hub :: Full page',
  },
  {
    expectedReactText: [
      'Tips',
      '권한 운영 팁',
      '승인은 리소스 영향 범위와 같이 봅니다',
      '예외 권한은 만료와 사유를 함께 관리합니다',
      '실행 주체보다 소유 주체를 먼저 읽힙니다',
      '연결 프로젝트 보기',
    ],
    expectedReferenceText: [
      'Tips',
      '권한 운영 팁',
      '권한 허브는 승인 상태, 역할 구성, 연결 리소스를 빠르게 읽을 수 있게 정리했습니다.',
      '승인은 리소스 영향 범위와 같이 봅니다',
      '예외 권한은 만료와 사유를 함께 관리합니다',
      '실행 주체보다 소유 주체를 먼저 읽힙니다',
      '연결 프로젝트 보기',
    ],
    name: 'Permission Hub permission operation tips',
    reactSelector:
      "xpath=//*[normalize-space()='권한 운영 팁']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: permissionHubReferenceFile,
    referenceSelector:
      "xpath=//*[normalize-space()='권한 운영 팁']/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(permissionHubReferenceFile),
    route: '/workspace/permissions',
    slug: 'permission-hub-operation-tips',
    trackerRow: 'Permission Hub :: Permission operation tips',
  },
  {
    expectedReactText: [
      'Guide Links',
      '권한 연계 허브',
      'Domain Hub',
      'Database Hub',
      'Consoles Hub',
      '런치패드로 돌아가기',
    ],
    expectedReferenceText: [
      'Guide Links',
      '권한 연계 허브',
      'Domain Hub',
      'Database Hub',
      'Consoles Hub',
      '런치패드로 돌아가기',
    ],
    name: 'Permission Hub guide links',
    reactSelector:
      "xpath=//*[normalize-space()='권한 연계 허브']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: permissionHubReferenceFile,
    referenceSelector:
      "xpath=//*[contains(normalize-space(),'Guide Links') and contains(normalize-space(),'권한 연계 허브')]/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(permissionHubReferenceFile),
    route: '/workspace/permissions',
    slug: 'permission-hub-guide-links',
    trackerRow: 'Permission Hub :: Guide links',
  },
  {
    expectedReactText: [
      'Storage · Data Plane',
      'Database Hub',
      '데이터베이스 리소스 모음입니다.',
      '새 데이터베이스 생성',
      'Consoles Hub 보기',
      '등록 리소스',
      'Running 7 · Issues 0',
      '연결 바인딩',
      'project / console bindings',
      'Healthy 리소스',
      'Degraded 0 · Unknown 4',
      '주간 리소스 열람',
      '최근 7일 조회 기준',
      'View',
      '전체',
      '벡터',
      '문서형',
      '관계형',
      '캐시',
      'Loaded 11 of 11 total',
    ],
    expectedReactAttributes: [
      {
        attribute: 'aria-pressed',
        label: 'React default all database filter active state',
        selector: 'button:has-text("전체")',
        value: 'true',
      },
      {
        attribute: 'aria-pressed',
        label: 'React vector database filter inactive state',
        selector: 'button:has-text("벡터")',
        value: 'false',
      },
    ],
    expectedReactDetailText: [
      '데이터베이스를 생성합니다',
      '먼저 사용할 DB 종류를 선택해주세요.',
      'DB 종류',
      'DB 정보',
      '생성 상태',
      'MongoDB',
      'MariaDB',
      'Elastic Search',
      'Postgresql',
      'Milvus',
      'redis',
      '다음',
      '취소',
    ],
    expectedReactLinks: [
      {
        href: '/workspace/consoles',
        label: 'Consoles Hub 보기',
      },
    ],
    expectedReactRequests: [
      'GET /api/v2/databases',
      'GET /api/v2/databases/stats',
      'GET /api/v2/databases/filters',
      'GET /api/v2/databases/panels/health',
    ],
    expectedReferenceText: [
      'Storage · Data Plane',
      'Database Hub',
      '데이터베이스 리소스 모음입니다.',
      '새 데이터베이스 생성',
      'Consoles Hub 보기',
      '등록 리소스',
      'Running 7 · Issues 0',
      '연결 바인딩',
      'project / console bindings',
      'Healthy 리소스',
      'Degraded 0 · Unknown 4',
      '주간 리소스 열람',
      '최근 7일 조회 기준',
      'View',
      '전체',
      '벡터',
      '문서형',
      '관계형',
      '캐시',
    ],
    expectedReferenceAttributes: [
      {
        attribute: 'aria-selected',
        label: 'reference default all database filter active state',
        selector: '[data-resource-filter="all"]',
        value: 'true',
      },
      {
        attribute: 'aria-selected',
        label: 'reference vector database filter inactive state',
        selector: '[data-resource-filter="vector"]',
        value: 'false',
      },
    ],
    expectedReferenceDetailText: [
      '데이터베이스를 생성합니다',
      '먼저 사용할 DB 종류를 선택해주세요.',
      'DB 종류',
      'DB 정보',
      '생성 상태',
      'MongoDB',
      'MariaDB',
      'Elastic Search',
      'Postgresql',
      'Milvus',
      'redis',
      '다음',
      '취소',
    ],
    expectedReferenceLinks: [
      {
        href: 'workspace_tools_hub.html',
        label: 'Consoles Hub 보기',
      },
    ],
    expectedReferenceRequests: [
      'GET /api/v2/databases',
      'GET /api/v2/databases/stats',
      'GET /api/v2/databases/filters',
      'GET /api/v2/databases/panels/health',
    ],
    name: 'Database Hub hero summary / filters',
    reactDetailActions: ['open-database-create-dialog'],
    reactDetailSelector: '[role="dialog"]',
    reactSelector:
      "xpath=//*[normalize-space()='Storage · Data Plane']/ancestor::*[contains(@class,'MuiStack-root')][1]",
    referenceDetailActions: ['open-database-create-dialog'],
    referenceDetailSelector: '#databaseCreateModal',
    referenceFile: databaseHubReferenceFile,
    referenceSelector: '.page',
    referenceUrl: toReferenceUrl(databaseHubReferenceFile),
    route: '/workspace/databases',
    slug: 'database-hub-hero-summary-filters',
    trackerRow: 'Database Hub :: Hero summary / filters',
  },
  {
    expectedReactText: [
      'Database Fleet',
      'Databases',
      '프로젝트 연결 보기',
      '11개의 데이터베이스 리소스를 API 기준으로 렌더링합니다.',
      'metric-turn-off',
      'sirius-mongodb',
      'dify-mv-jean',
      'jean-milvus-test',
      'Backup 없음',
      'Storage',
      'Restart',
    ],
    expectedReactLinks: [
      {
        href: '/workspace/projects',
        label: '프로젝트 연결 보기',
      },
    ],
    expectedReactRequests: [
      'GET /api/v2/databases',
      'GET /api/v2/databases/6a0d0a5b0f75fd60c72f0782/bindings',
      'GET /api/v2/databases/69d7027fd4b8dae70bc092df/bindings',
    ],
    expectedReferenceText: [
      'Database Fleet',
      'Databases',
      '프로젝트 연결 보기',
      '11개의 데이터베이스 리소스를 API 기준으로 렌더링합니다.',
      'metric-turn-off',
      'sirius-mongodb',
      'dify-mv-jean',
      'jean-milvus-test',
      'Backup 없음',
      'Storage',
      'Restart',
    ],
    expectedReferenceLinks: [
      {
        href: 'workspace_projects_hub.html',
        label: '프로젝트 연결 보기',
      },
    ],
    expectedReferenceRequests: [
      'GET /api/v2/databases',
      'GET /api/v2/databases/6a0d0a5b0f75fd60c72f0782/bindings',
      'GET /api/v2/databases/69d7027fd4b8dae70bc092df/bindings',
    ],
    name: 'Database Hub database cards',
    reactSelector:
      "xpath=//*[normalize-space()='Database Fleet']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: databaseHubReferenceFile,
    referenceSelector: '#resource-panel',
    referenceUrl: toReferenceUrl(databaseHubReferenceFile),
    route: '/workspace/databases',
    slug: 'database-hub-database-cards',
    trackerRow: 'Database Hub :: Database cards',
  },
  {
    expectedReactText: [
      'Tips',
      '데이터 리소스 운영 팁',
      '리소스 카드에서는 제어 판단에 필요한 정보만 남기고, 운영 참고는 패널에서 짧게 확인합니다.',
      'Running 리소스는 영향 범위를 먼저 봅니다',
      '재기동 전 어떤 프로젝트가 붙어 있는지 Bound Projects 기준으로 확인합니다.',
      'Stopped 리소스는 별도 운영 흐름으로 다룹니다',
      '실험성 또는 비상시 리소스는 카드에서 직접 기동하지 않는 전제를 둡니다.',
      '연결 콘솔은 카드 밖 링크로 이동합니다',
      'DB 허브는 리소스 파악에 집중하고 접속 행위는 Consoles Hub로 넘깁니다.',
      '연결 프로젝트 보기',
    ],
    expectedReactLinks: [
      {
        href: '/workspace/projects',
        label: '연결 프로젝트 보기',
      },
    ],
    expectedReactRequests: ['GET /api/v2/panels/tips?surface=databases'],
    expectedReferenceText: [
      'Tips',
      '데이터 리소스 운영 팁',
      '리소스 카드에서는 제어 판단에 필요한 정보만 남기고, 운영 참고는 패널에서 짧게 확인합니다.',
      'Running 리소스는 영향 범위를 먼저 봅니다',
      '재기동 전 어떤 프로젝트가 붙어 있는지 Bound Projects 기준으로 확인합니다.',
      'Stopped 리소스는 별도 운영 흐름으로 다룹니다',
      '실험성 또는 비상시 리소스는 카드에서 직접 기동하지 않는 전제를 둡니다.',
      '연결 콘솔은 카드 밖 링크로 이동합니다',
      'DB 허브는 리소스 파악에 집중하고 접속 행위는 Consoles Hub로 넘깁니다.',
      '연결 프로젝트 보기',
    ],
    expectedReferenceLinks: [
      {
        href: '/workspace/projects',
        label: '연결 프로젝트 보기',
      },
    ],
    expectedReferenceRequests: ['GET /api/v2/panels/tips?surface=databases'],
    name: 'Database Hub database operation tips',
    reactSelector:
      "xpath=//*[normalize-space()='데이터 리소스 운영 팁']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: databaseHubReferenceFile,
    referenceSelector:
      "xpath=//*[normalize-space()='데이터 리소스 운영 팁']/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(databaseHubReferenceFile),
    route: '/workspace/databases',
    slug: 'database-hub-operation-tips',
    trackerRow: 'Database Hub :: Database operation tips',
  },
  {
    expectedReactText: [
      'Guide Links',
      '데이터 운영 연계 허브',
      '데이터 리소스 상태와 실제 운영 콘솔을 이어서 확인할 수 있습니다.',
      'Consoles Hub',
      '각 DB 리소스에 연결된 운영 콘솔을 엽니다.',
      'Permission Hub',
      '운영 DB 접근 방식과 읽기 전용 기준을 확인합니다.',
      'Projects Hub',
      '리소스가 연결된 프로젝트 맥락을 확인합니다.',
      '런치패드로 돌아가기',
    ],
    expectedReactLinks: [
      {
        href: '/workspace/consoles',
        label: 'Consoles Hub',
      },
      {
        href: '/workspace/permissions',
        label: 'Permission Hub',
      },
      {
        href: '/workspace/projects',
        label: 'Projects Hub',
      },
      {
        href: '/launchpad',
        label: '런치패드로 돌아가기',
      },
    ],
    expectedReactRequests: ['GET /api/v2/panels/guide-links?surface=databases'],
    expectedReferenceAttributes: [
      {
        attribute: 'href',
        label: 'reference Consoles Hub guide CTA',
        selector: '.hub-briefing-route:has-text("Consoles Hub") .hub-briefing-route-link',
        value: '/workspace/consoles',
      },
      {
        attribute: 'href',
        label: 'reference Permission Hub guide CTA',
        selector: '.hub-briefing-route:has-text("Permission Hub") .hub-briefing-route-link',
        value: '/workspace/permissions',
      },
      {
        attribute: 'href',
        label: 'reference Projects Hub guide CTA',
        selector: '.hub-briefing-route:has-text("Projects Hub") .hub-briefing-route-link',
        value: '/workspace/projects',
      },
    ],
    expectedReferenceText: [
      'Guide Links',
      '데이터 운영 연계 허브',
      '데이터 리소스 상태와 실제 운영 콘솔을 이어서 확인할 수 있습니다.',
      'Consoles Hub',
      '각 DB 리소스에 연결된 운영 콘솔을 엽니다.',
      'Permission Hub',
      '운영 DB 접근 방식과 읽기 전용 기준을 확인합니다.',
      'Projects Hub',
      '리소스가 연결된 프로젝트 맥락을 확인합니다.',
      '바로가기',
      '런치패드로 돌아가기',
    ],
    expectedReferenceLinks: [
      {
        href: '/launchpad',
        label: '런치패드로 돌아가기',
      },
    ],
    expectedReferenceRequests: ['GET /api/v2/panels/guide-links?surface=databases'],
    name: 'Database Hub guide links',
    reactSelector:
      "xpath=//*[normalize-space()='데이터 운영 연계 허브']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: databaseHubReferenceFile,
    referenceSelector:
      "xpath=//*[contains(normalize-space(),'Guide Links') and contains(normalize-space(),'데이터 운영 연계 허브')]/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(databaseHubReferenceFile),
    route: '/workspace/databases',
    slug: 'database-hub-guide-links',
    trackerRow: 'Database Hub :: Guide links',
  },
  {
    expectedReactText: [
      'Running Health',
      '현재 Running 리소스 Healthy',
      '세부 이상 감지는 K8s/infra 이벤트 기준으로 확인합니다. 우측 레일은 지금 실행 중인 데이터 리소스의 헬시 상태만 보여줍니다.',
      '현재 모니터링 중인 리소스',
      'live snapshot',
      'Healthy',
      '7',
      'Needs Action',
      '0',
      'Unknown',
      '4',
      'dify-mv-jean',
      '런타임 상태를 아직 확인하지 못했습니다.',
      'jean-milvus-test',
      'metric-turn-off',
      'yg-milvus-test-1',
      'jean-test',
      '최근 상태 점검 기준으로 이상 징후가 없습니다.',
      'Unknown',
      'Healthy',
    ],
    expectedReactLocatorText: [
      {
        label: 'React health rail monitored count',
        selector:
          "xpath=.//*[normalize-space()='현재 모니터링 중인 리소스']/preceding-sibling::*[1]",
        text: '11',
      },
      {
        label: 'React health rail Healthy count',
        selector: "xpath=(.//*[normalize-space()='Healthy']/following-sibling::*[1])[1]",
        text: '7',
      },
      {
        label: 'React health rail Needs Action count',
        selector: "xpath=.//*[normalize-space()='Needs Action']/following-sibling::*[1]",
        text: '0',
      },
      {
        label: 'React health rail Unknown count',
        selector: "xpath=(.//*[normalize-space()='Unknown']/following-sibling::*[1])[1]",
        text: '4',
      },
    ],
    expectedReactRequests: ['GET /api/v2/databases/panels/health'],
    expectedReferenceText: [
      'Running Health',
      '현재 Running 리소스 Healthy',
      '세부 이상 감지는 K8s/infra 이벤트 기준으로 확인합니다. 우측 레일은 지금 실행 중인 데이터 리소스의 헬시 상태만 보여줍니다.',
      '현재 모니터링 중인 리소스',
      'live snapshot',
      'Healthy',
      '7',
      'Needs Action',
      '0',
      'Unknown',
      '4',
      'dify-mv-jean',
      '런타임 상태를 아직 확인하지 못했습니다.',
      'jean-milvus-test',
      'metric-turn-off',
      'yg-milvus-test-1',
      'jean-test',
      '최근 상태 점검 기준으로 이상 징후가 없습니다.',
      'Unknown',
      'Healthy',
    ],
    expectedReferenceLocatorText: [
      {
        label: 'reference health rail monitored count',
        selector: '.hub-briefing-overview-value',
        text: '11',
      },
      {
        label: 'reference health rail Healthy count',
        selector: '.hub-briefing-overview-stat:has-text("Healthy") .hub-briefing-overview-number',
        text: '7',
      },
      {
        label: 'reference health rail Needs Action count',
        selector:
          '.hub-briefing-overview-stat:has-text("Needs Action") .hub-briefing-overview-number',
        text: '0',
      },
      {
        label: 'reference health rail Unknown count',
        selector: '.hub-briefing-overview-stat:has-text("Unknown") .hub-briefing-overview-number',
        text: '4',
      },
    ],
    expectedReferenceRequests: ['GET /api/v2/databases/panels/health'],
    name: 'Database Hub health rail',
    reactSelector:
      "xpath=//*[normalize-space()='현재 Running 리소스 Healthy']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: databaseHubReferenceFile,
    referenceSelector:
      "xpath=//aside[contains(@class,'side-col')][contains(normalize-space(),'Running Health') and contains(normalize-space(),'현재 Running 리소스 Healthy')]",
    referenceUrl: toReferenceUrl(databaseHubReferenceFile),
    route: '/workspace/databases',
    slug: 'database-hub-health-rail',
    trackerRow: 'Database Hub :: Health rail',
  },
  {
    expectedReactText: [
      'Development · Database Consoles',
      'Consoles Hub',
      '데이터베이스 콘솔 모음입니다.',
      '새 콘솔 생성',
      'Database Hub 보기',
      '등록 콘솔',
      '8',
      'Bound DB',
      '5',
      'Running 콘솔',
      '0',
      'Stopped 콘솔',
      'View',
      '전체',
      'Attu',
      'phpMyAdmin',
      'pgAdmin',
      'Mongo GUI',
      'Redis Insight',
      'Loaded 8 of 8 total',
    ],
    expectedReferenceText: [
      'Development · Database Consoles',
      'Consoles Hub',
      '데이터베이스 콘솔 모음입니다.',
      '새 콘솔 생성',
      'Database Hub 보기',
      '등록 콘솔',
      '8',
      '연결 엔드포인트',
      '5',
      '워크스페이스 연결',
      '4',
      '주간 콘솔 진입',
      '현재 집계 API 미지원',
      'View',
      '전체',
      '관계형',
      '문서형',
      '캐시',
      '검색',
      '벡터',
    ],
    name: 'Consoles Hub hero summary / filters',
    reactSelector: 'main',
    referenceFile: consoleHubReferenceFile,
    referenceSelector: '.page',
    referenceUrl: toReferenceUrl(consoleHubReferenceFile),
    route: '/workspace/consoles',
    slug: 'consoles-hub-hero-summary-filters',
    trackerRow: 'Consoles Hub :: Hero summary / filters',
  },
  {
    expectedReactText: [
      'Tips',
      '콘솔 운영 팁',
      '콘솔 카드는 실행과 연결 판단에 필요한 정보만 남기고, 운영 참고는 하단 패널에서 짧게 확인합니다.',
      'Running 콘솔만 상태 판단을 우선합니다',
      'Open 전에 연결 DB를 먼저 확인합니다',
      '이상 감지는 콘솔 카드보다 이벤트 흐름에서 확인합니다',
      '연결 DB 보기',
    ],
    expectedReferenceText: [
      'Tips',
      '콘솔 운영 팁',
      '운영 팁을 불러오는 중입니다.',
      'Running 콘솔만 상태 판단을 우선합니다',
      'Open 전에 연결 DB를 먼저 확인합니다',
      '이상 감지는 콘솔 카드보다 이벤트 흐름에서 확인합니다',
      '연결 DB 보기',
    ],
    name: 'Consoles Hub console operation tips',
    reactSelector:
      "xpath=//*[normalize-space()='콘솔 운영 팁']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: consoleHubReferenceFile,
    referenceSelector:
      "xpath=//*[normalize-space()='콘솔 운영 팁']/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(consoleHubReferenceFile),
    route: '/workspace/consoles',
    slug: 'consoles-hub-operation-tips',
    trackerRow: 'Consoles Hub :: Console operation tips',
  },
  {
    expectedReactText: [
      'Guide Links',
      '관련 허브 바로가기',
      '콘솔 사용 중 자주 이어지는 허브와 운영 정책 문서를 함께 제공합니다.',
      'Database Hub',
      'Permission Hub',
      'Projects Hub',
      '런치패드로 돌아가기',
    ],
    expectedReferenceText: [
      'Guide Links',
      '가이드 링크',
      '가이드 링크를 불러오는 중입니다.',
      'Database Hub',
      'Permission Hub',
      'Projects Hub',
      '런치패드로 돌아가기',
    ],
    name: 'Consoles Hub guide links',
    reactSelector:
      "xpath=//*[normalize-space()='관련 허브 바로가기']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: consoleHubReferenceFile,
    referenceSelector:
      "xpath=//*[normalize-space()='가이드 링크']/ancestor::section[contains(@class,'panel')][1]",
    referenceUrl: toReferenceUrl(consoleHubReferenceFile),
    route: '/workspace/consoles',
    slug: 'consoles-hub-guide-links',
    trackerRow: 'Consoles Hub :: Guide links',
  },
  {
    expectedReactText: [
      'Running Health',
      '현재 console runtime 상태',
      'Runtime summary',
      '8 total',
      'Running 0',
      'Stopped 8',
      'dsadas',
      'fdsfds',
      'jean-test',
      'jean-tool-test',
      'sirius-uv',
    ],
    expectedReferenceText: [
      'Running Health',
      '현재 Running 콘솔 Healthy',
      'dsadas',
      'fdsfds',
      'jean-test',
      'jean-tool-test',
      'sirius-uv',
      'Stopped',
    ],
    name: 'Consoles Hub health rail',
    reactSelector:
      "xpath=//*[normalize-space()='현재 console runtime 상태']/ancestor::*[contains(@class,'MuiPaper-root')][1]",
    referenceFile: consoleHubReferenceFile,
    referenceSelector:
      "xpath=//aside[contains(@class,'side-col')][contains(normalize-space(),'Running Health') and contains(normalize-space(),'현재 Running 콘솔 Healthy')]",
    referenceUrl: toReferenceUrl(consoleHubReferenceFile),
    route: '/workspace/consoles',
    slug: 'consoles-hub-health-rail',
    trackerRow: 'Consoles Hub :: Health rail',
  },
];
