import type { SectionStatusInfo } from '@/components/reference-status';

export const launchpadSectionStatus = {
  aiGalleryPreview: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' }],
    evidence: 'Verified with browser comparison and pnpm check.',
    fieldsUsed: [
      'storeSpotlight.items[].title',
      'storeSpotlight.items[].description',
      'storeSpotlight.items[].href',
      'storeSpotlight.aiSpotlight.title',
      'storeSpotlight.aiSpotlight.summary',
      'storeSpotlight.aiSpotlight.statusLabel',
      'storeSpotlight.aiSpotlight.tags',
    ],
    id: 'launchpad-ai-gallery-preview',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'AI Gallery preview',
  },
  appGalleryPreview: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' }],
    evidence: 'Verified with browser comparison and pnpm check.',
    fieldsUsed: [
      'storeSpotlight.items[].title',
      'storeSpotlight.items[].description',
      'storeSpotlight.items[].href',
      'storeSpotlight.featuredApps[].title',
      'storeSpotlight.featuredApps[].subtitle',
      'storeSpotlight.featuredApps[].summary',
      'storeSpotlight.featuredApps[].tags',
      'storeSpotlight.featuredApps[].badge',
    ],
    id: 'launchpad-app-gallery-preview',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'App Gallery preview',
  },
  articles: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' }],
    evidence: 'Verified with browser comparison and pnpm check.',
    fieldsUsed: [
      'articles.items[].title',
      'articles.items[].category',
      'articles.items[].href',
      'articles.tabs[].value',
      'articles.tabs[].label',
    ],
    id: 'launchpad-articles',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'Articles panel',
  },
  banner: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' }],
    evidence:
      'Verified against the current portal banner fallback behavior with focused and broad visual checks plus project checks.',
    fieldsUsed: [
      'hero.title',
      'hero.subtitle',
      'hero.workspaceName',
      'hero.heroStats[].label',
      'hero.heroStats[].value',
      'hero.heroStats[].note',
      'serviceMenu.items[].title',
      'serviceMenu.items[].links[].label',
      'serviceMenu.items[].links[].href',
      'announcements.items[].title',
      'announcements.items[].message',
      'announcements.items[].type',
      'announcements.items[].href',
    ],
    id: 'launchpad-banner-rail',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'Banner rail',
  },
  deploymentsRail: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/my-work' }],
    evidence: 'Verified with mock endpoint smoke and pnpm check.',
    fieldsUsed: [
      'projects.items[].name',
      'projects.items[].status',
      'projects.items[].projectType',
      'jobs.items[].name',
      'jobs.items[].status',
      'jobs.items[].progress',
      'summary.recentJobStatus.running',
      'summary.recentJobStatus.failed',
    ],
    id: 'launchpad-my-deployments',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'My deployments rail',
  },
  guides: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' }],
    evidence: 'Verified with browser comparison and pnpm check.',
    fieldsUsed: ['guides.title', 'guides.rows[].title', 'guides.footerLink.href'],
    id: 'launchpad-guides',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'Guides panel',
  },
  hero: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' }],
    evidence: 'Focused Playwright visual target and pnpm check passed.',
    fieldsUsed: [
      'hero.title',
      'hero.subtitle',
      'hero.workspaceName',
      'hero.heroStats[].label',
      'hero.heroStats[].value',
      'hero.heroStats[].trend',
    ],
    id: 'launchpad-hero',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'Personalized hero/header',
  },
  notificationsRail: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/my-work' }],
    evidence: 'Verified with mock endpoint smoke and pnpm check.',
    fieldsUsed: [
      'notifications.items[].title',
      'notifications.items[].isUnread',
      'notifications.total',
    ],
    id: 'launchpad-my-notifications',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'My notifications rail',
  },
  resourcesRail: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/resources' }],
    evidence: 'Verified with mock endpoint smoke and pnpm check.',
    fieldsUsed: [
      'databases.items[].name',
      'databases.items[].status',
      'databases.items[].health.label',
      'buckets.items[].name',
      'buckets.items[].status',
      'domains.items[].name',
      'domains.items[].status',
      'consoles.items[].name',
      'consoles.items[].statusLabel',
    ],
    id: 'launchpad-my-resources',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'My resources rail',
  },
} satisfies Record<string, SectionStatusInfo>;
