import type { SectionStatusInfo } from '@/components/reference-status';

export const launchpadSectionStatus = {
  aiGalleryPreview: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' }],
    evidence:
      'React keeps the static reference section description and renders tag-derived AI strip cards from accepted overview fields; focused typecheck and lint passed, with Playwright acceptance pending.',
    fieldsUsed: [
      'storeSpotlight.items[].title',
      'storeSpotlight.items[].href',
      'storeSpotlight.aiSpotlight.title',
      'storeSpotlight.aiSpotlight.summary',
      'storeSpotlight.aiSpotlight.statusLabel',
      'storeSpotlight.aiSpotlight.tags',
    ],
    id: 'launchpad-ai-gallery-preview',
    page: 'Launchpad',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'AI Gallery preview',
  },
  appGalleryPreview: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' }],
    evidence:
      'React keeps the static reference section description and renders App Gallery preview cards from accepted overview fields; focused typecheck and lint passed, with Playwright acceptance pending.',
    fieldsUsed: [
      'storeSpotlight.items[].title',
      'storeSpotlight.items[].href',
      'storeSpotlight.featuredApps[].title',
      'storeSpotlight.featuredApps[].subtitle',
      'storeSpotlight.featuredApps[].summary',
      'storeSpotlight.featuredApps[].tags',
      'storeSpotlight.featuredApps[].badge',
    ],
    id: 'launchpad-app-gallery-preview',
    page: 'Launchpad',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'App Gallery preview',
  },
  articles: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' }],
    evidence: 'Verified with browser comparison and pnpm check.',
    fieldsUsed: [
      'articles.items[].title',
      'articles.items[].category',
      'articles.items[].href',
      'articles.tabs[].value',
      'articles.tabs[].label',
    ],
    id: 'launchpad-articles',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'Articles panel',
  },
  banner: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' }],
    evidence:
      'React now follows the accepted user-provided overview sample payload for API-backed banners, source ordering, action links, chip text, visual modes, and announcement fallback behavior; focused typecheck and lint passed, with Playwright acceptance pending.',
    fieldsUsed: [
      'banners[].id',
      'banners[].status',
      'banners[].theme',
      'banners[].visualMode',
      'banners[].showBackdrop',
      'banners[].type',
      'banners[].title',
      'banners[].message',
      'banners[].eyebrow',
      'banners[].eyebrowIcon',
      'banners[].href',
      'banners[].chips',
      'banners[].priority',
      'banners[].pinned',
      'banners[].primaryAction.label',
      'banners[].primaryAction.href',
      'banners[].primaryAction.icon',
      'banners[].secondaryAction.label',
      'banners[].secondaryAction.href',
      'banners[].secondaryAction.icon',
      'banners[].snapshotTitle',
      'banners[].snapshotRows[].title',
      'banners[].snapshotRows[].description',
      'banners[].visualTitle',
      'banners[].visualMeta',
      'banners[].visualIcon',
      'announcements.items[].title',
      'announcements.items[].message',
      'announcements.items[].type',
      'announcements.items[].href',
    ],
    id: 'launchpad-banner-rail',
    page: 'Launchpad',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'Banner rail',
  },
  deploymentsRail: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/my-work' }],
    evidence:
      'React renders deployment summary chips and rows from accepted my-work fields; focused typecheck and lint passed, with Playwright acceptance pending.',
    fieldsUsed: [
      'summary.projectCount',
      'summary.ideCount',
      'summary.jobCount',
      'projects.items[].name',
      'projects.items[].status',
      'projects.items[].projectType',
      'jobs.items[].type',
      'jobs.items[].status',
      'jobs.items[].progress',
      'summary.recentJobStatus.running',
      'summary.recentJobStatus.failed',
    ],
    id: 'launchpad-my-deployments',
    page: 'Launchpad',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'My deployments rail',
  },
  guides: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' }],
    evidence: 'Verified with browser comparison and pnpm check.',
    fieldsUsed: ['guides.title', 'guides.rows[].title', 'guides.footerLink.href'],
    id: 'launchpad-guides',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'Guides panel',
  },
  hero: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/overview' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/my-work' },
    ],
    evidence:
      'React derives the hero subtitle from accepted my-work summary fields and keeps title/stat rendering on accepted overview fields; focused typecheck and lint passed, with Playwright acceptance pending.',
    fieldsUsed: [
      'hero.title',
      'hero.subtitle',
      'hero.userName',
      'hero.heroStats[].label',
      'hero.heroStats[].value',
      'hero.heroStats[].icon',
      'hero.heroStats[].color',
      'summary.unreadNotificationCount',
      'summary.recentJobStatus.running',
    ],
    id: 'launchpad-hero',
    page: 'Launchpad',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'Personalized hero/header',
  },
  notificationsRail: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/my-work' }],
    evidence: 'Verified with mock endpoint smoke and pnpm check.',
    fieldsUsed: [
      'notifications.items[].title',
      'notifications.items[].isUnread',
      'notifications.total',
    ],
    id: 'launchpad-my-notifications',
    page: 'Launchpad',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'My notifications rail',
  },
  resourcesRail: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/launchpad/resources' }],
    evidence:
      'React renders resource summary chips and rail rows from accepted resources fields; focused typecheck and lint passed, with Playwright acceptance pending.',
    fieldsUsed: [
      'summary.totalResources',
      'summary.attentionCount',
      'summary.totalBindings',
      'databases.items[].name',
      'databases.items[].status',
      'databases.items[].health.label',
      'buckets.items[].name',
      'buckets.items[].status',
      'domains.items[].name',
      'domains.items[].status',
      'consoles.items[].name',
      'consoles.items[].statusLabel',
    ],
    id: 'launchpad-my-resources',
    page: 'Launchpad',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'portal_launchpad.html',
    section: 'My resources rail',
  },
} satisfies Record<string, SectionStatusInfo>;
