import type { SectionStatusInfo } from '@/components/reference-status';

export const consoleHubSectionStatus = {
  cards: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/consoles?cursor=&sort=&limit=&q=' },
      { contract: 'missing', method: 'GET', path: '/api/v2/consoles/:id' },
      { contract: 'missing', method: 'POST', path: '/api/v2/consoles' },
      { contract: 'missing', method: 'DELETE', path: '/api/v2/consoles/:id' },
      { contract: 'missing', method: 'POST', path: '/api/v2/consoles/:id/start' },
      { contract: 'missing', method: 'POST', path: '/api/v2/consoles/:id/stop' },
      { contract: 'missing', method: 'POST', path: '/api/v2/consoles/:id/open' },
      { contract: 'missing', method: 'GET', path: '/api/v2/consoles/:id/bindings' },
      { contract: 'missing', method: 'POST', path: '/api/v2/consoles/:id/bindings' },
      { contract: 'missing', method: 'DELETE', path: '/api/v2/consoles/:id/bindings/:dbId' },
    ],
    blockers: [
      'Missing accepted response contract for GET /api/v2/consoles/:id, so console detail navigation remains disabled.',
      'Missing accepted response contracts for POST /api/v2/consoles, DELETE /api/v2/consoles/:id, POST /api/v2/consoles/:id/start, POST /api/v2/consoles/:id/stop, POST /api/v2/consoles/:id/open, GET /api/v2/consoles/:id/bindings, POST /api/v2/consoles/:id/bindings, and DELETE /api/v2/consoles/:id/bindings/:dbId, so lifecycle and binding behavior remains disabled.',
    ],
    evidence: 'Accepted user-provided list payload supports read-only console card rendering.',
    fieldsUsed: [
      'items[].name',
      'items[].slug',
      'items[].summary',
      'items[].typeLabel',
      'items[].status',
      'items[].statusLabel',
      'items[].icon',
      'items[].bindingCount',
      'items[].bindings[].name',
      'items[].bindings[].engine',
      'items[].health.label',
      'items[].health.message',
      'items[].owner.displayName',
      'items[].owner.email',
      'items[].capabilities.canOpen',
      'items[].capabilities.canStart',
      'items[].capabilities.canStop',
      'items[].capabilities.canDelete',
      'items[].capabilities.canManageBindings',
    ],
    id: 'console-hub-cards',
    nextAction:
      'Provide or approve contracts for the listed console detail, lifecycle, open, and binding endpoints.',
    page: 'Consoles Hub',
    progress: 'blocked',
    readiness: 'Blocked',
    reference: 'workspace_tools_hub.html',
    section: 'Console cards',
  },
  filters: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/consoles/filters' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/consoles?cursor=&sort=&limit=&q=' },
    ],
    evidence: 'Accepted user-provided filters payload drives console type filter chips.',
    fieldsUsed: [
      'types[].value',
      'types[].label',
      'types[].count',
      'statuses[].count',
      'page.total',
    ],
    id: 'console-hub-filters',
    page: 'Consoles Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_tools_hub.html',
    section: 'Filter bar',
  },
  guideLinks: {
    apis: [
      {
        contract: 'accepted',
        method: 'GET',
        path: '/api/v2/consoles/panels/guide-links',
      },
    ],
    evidence: 'Accepted user-provided guide-links payload drives the related hubs panel.',
    fieldsUsed: [
      'title',
      'description',
      'rows[].title',
      'rows[].meta',
      'rows[].href',
      'footerLink.href',
    ],
    id: 'console-hub-guide-links',
    page: 'Consoles Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_tools_hub.html',
    section: 'Guide links',
  },
  healthRail: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/consoles/panels/health' }],
    evidence: 'Accepted user-provided health panel payload drives the runtime status rail.',
    fieldsUsed: [
      'label',
      'title',
      'summary.total',
      'summary.running',
      'summary.stopped',
      'summary.error',
      'rows[].title',
      'rows[].meta',
      'rows[].pill.label',
      'rows[].pill.tone',
    ],
    id: 'console-hub-health-rail',
    page: 'Consoles Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_tools_hub.html',
    section: 'Health rail',
  },
  hero: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/consoles/stats' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/consoles/filters' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/consoles?cursor=&sort=&limit=&q=' },
      { contract: 'deferred', method: 'GET', path: '/api/v2/search?q=&types=projects,domains,...' },
    ],
    blockers: [
      'Missing accepted response contract for POST /api/v2/consoles, so the create-console CTA remains disabled.',
      'Missing accepted response contract for shared global search, so cross-resource search remains deferred to shared search work.',
    ],
    evidence:
      'Accepted user-provided stats, filters, and list payloads support the console summary.',
    fieldsUsed: [
      'totalConsoles',
      'runningCount',
      'stoppedCount',
      'issueCount',
      'bindingCount',
      'types[].count',
      'types[].label',
      'statuses[].count',
    ],
    id: 'console-hub-hero',
    nextAction:
      'Provide create-console and shared search contracts before enabling those behaviors.',
    page: 'Consoles Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_tools_hub.html',
    section: 'Hero summary',
  },
  tips: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/consoles/panels/tips' }],
    evidence: 'Accepted user-provided tips payload drives the console operation tips panel.',
    fieldsUsed: ['title', 'description', 'rows[].title', 'rows[].meta', 'footerLink.href'],
    id: 'console-hub-tips',
    page: 'Consoles Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_tools_hub.html',
    section: 'Console operation tips',
  },
} satisfies Record<string, SectionStatusInfo>;
