import type { SectionStatusInfo } from '@/components/reference-status';

export const domainHubSectionStatus = {
  cards: {
    apis: [
      {
        contract: 'accepted',
        method: 'GET',
        path: '/api/v2/domains?sort=&limit=8&cursor=',
      },
      { contract: 'missing', method: 'GET', path: '/api/v2/domains/:id' },
    ],
    blockers: [
      'Missing accepted response contract for GET /api/v2/domains/:id, so domain card detail behavior cannot be verified.',
    ],
    evidence:
      'Accepted list sample renders the visible domain card body, status, certificate copy, connection copy, and footer note.',
    fieldsUsed: [
      'items[].name',
      'items[].description',
      'items[].status',
      'items[].kind',
      'items[].certificate.status',
      'items[].connection.status',
      'items[].boundProject',
      'items[].capabilities.canEdit',
    ],
    id: 'domain-hub-cards',
    nextAction: 'Provide or approve the Domain Detail GET /api/v2/domains/:id contract.',
    page: 'Domain Hub',
    progress: 'blocked',
    readiness: 'Blocked',
    reference: 'workspace_domain_hub.html',
    section: 'Domain cards',
  },
  certificateRail: {
    apis: [
      {
        contract: 'accepted',
        method: 'GET',
        path: '/api/v2/domains?sort=&limit=8&cursor=',
      },
      { contract: 'accepted', method: 'GET', path: '/api/v2/domains/panels/certificates' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/domains/:id/certificate' },
    ],
    evidence:
      'Accepted list, certificate panel, and selected-domain certificate samples render the reference per-domain certificate rows plus panel description.',
    fieldsUsed: [
      'items[].id',
      'items[].name',
      'items[].certificate.status',
      'panel.items[].status',
      'panel.items[].count',
      'panel.total',
      'detail.id',
      'detail.name',
      'detail.status',
    ],
    id: 'domain-hub-certificate-rail',
    page: 'Domain Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_domain_hub.html',
    section: 'Certificate rail',
  },
  connectionRail: {
    apis: [
      {
        contract: 'accepted',
        method: 'GET',
        path: '/api/v2/domains?sort=&limit=8&cursor=',
      },
      { contract: 'accepted', method: 'GET', path: '/api/v2/domains/panels/connections' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/domains/:id/connection' },
    ],
    evidence:
      'Accepted list, connection panel, and selected-domain connection samples render the reference per-domain connection rows plus panel description.',
    fieldsUsed: [
      'items[].id',
      'items[].name',
      'items[].connection.status',
      'items[].boundProject',
      'panel.items[].status',
      'panel.items[].count',
      'panel.total',
      'detail.id',
      'detail.name',
      'detail.status',
      'detail.boundProject',
    ],
    id: 'domain-hub-connection-rail',
    page: 'Domain Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_domain_hub.html',
    section: 'Connection rail',
  },
  filters: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/domains/filters' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/domains (paged)' },
    ],
    evidence: 'Reference chip set implemented from accepted status/certificate fields.',
    fieldsUsed: ['statuses[]', 'certificateStatuses[]', 'connectionStatuses[]', 'page.total'],
    id: 'domain-hub-filters',
    page: 'Domain Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_domain_hub.html',
    section: 'Filter bar',
  },
  guideLinks: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/panels/guide-links?surface=domains' },
    ],
    evidence: 'Verified with Playwright/browser comparison and pnpm check.',
    fieldsUsed: ['title', 'description', 'rows[].title', 'rows[].href', 'footerLink.href'],
    id: 'domain-hub-guide-links',
    page: 'Domain Hub',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'workspace_domain_hub.html',
    section: 'Guide links',
  },
  hero: {
    apis: [
      {
        contract: 'accepted',
        method: 'GET',
        path: '/api/v2/domains?sort=&limit=8&cursor=',
      },
      { contract: 'accepted', method: 'GET', path: '/api/v2/domains/stats' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/domains/filters' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/domains/panels/certificates' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/domains/panels/connections' },
      { contract: 'accepted', method: 'POST', path: '/api/v2/domains' },
    ],
    evidence:
      'Accepted stats/list/panel samples render the reference hero stat labels and notes; accepted create-domain request/response powers the enabled modal submit flow.',
    fieldsUsed: [
      'total',
      'connected',
      'pending',
      'review',
      'items[].boundProject',
      'certificatePanel.items[].status',
      'certificatePanel.items[].count',
      'connectionPanel.items[].status',
      'connectionPanel.items[].count',
      'create.url',
      'create.data.id',
    ],
    id: 'domain-hub-hero',
    page: 'Domain Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_domain_hub.html',
    section: 'Hero summary',
  },
  tips: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/panels/tips?surface=domains' }],
    evidence: 'Verified with mock endpoint smoke, route smoke, and pnpm check.',
    fieldsUsed: ['title', 'description', 'rows[].title', 'rows[].meta', 'footerLink.href'],
    id: 'domain-hub-tips',
    page: 'Domain Hub',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'workspace_domain_hub.html',
    section: 'DNS operation tips',
  },
} satisfies Record<string, SectionStatusInfo>;
