import type { SectionStatusInfo } from '@/components/reference-status';

export const bucketHubSectionStatus = {
  cards: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/buckets?cursor=&sort=&limit=&q=' },
      { contract: 'missing', method: 'GET', path: '/api/v2/buckets/:id' },
      { contract: 'missing', method: 'POST', path: '/api/v2/buckets' },
      { contract: 'missing', method: 'PATCH', path: '/api/v2/buckets/:id' },
      { contract: 'missing', method: 'DELETE', path: '/api/v2/buckets/:id' },
      { contract: 'missing', method: 'POST', path: '/api/v2/buckets/:id/bind' },
      { contract: 'missing', method: 'DELETE', path: '/api/v2/buckets/:id/bind/:projectId' },
      { contract: 'missing', method: 'POST', path: '/api/v2/buckets/:id/open' },
    ],
    blockers: [
      'Missing accepted response contract for GET /api/v2/buckets/:id, so bucket detail navigation remains disabled.',
      'Missing accepted response contracts for create, edit, delete, bind, unbind, and open actions; card action buttons remain disabled.',
    ],
    evidence: 'Read-only bucket cards use the accepted paged bucket list payload.',
    fieldsUsed: [
      'items[].id',
      'items[].name',
      'items[].type',
      'items[].status',
      'items[].capacity.label',
      'items[].usage.label',
      'items[].usage.usagePercent',
      'items[].owner.displayName',
      'items[].owner.email',
      'items[].collaborators[].displayName',
      'items[].boundProjectCount',
      'page.total',
    ],
    id: 'bucket-hub-cards',
    nextAction: 'Provide or approve contracts for the listed bucket detail and action endpoints.',
    page: 'Bucket Hub',
    progress: 'in-progress',
    readiness: 'Blocked',
    reference: 'workspace_s3_hub.html',
    section: 'Bucket cards',
  },
  guideLinks: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/panels/guide-links?surface=buckets' },
    ],
    evidence:
      'Focused Playwright target, broader visual suite, and project checks passed with the accepted usage payload.',
    fieldsUsed: [
      'title',
      'description',
      'rows[].title',
      'rows[].meta',
      'rows[].href',
      'footerLink.href',
    ],
    id: 'bucket-hub-guide-links',
    page: 'Bucket Hub',
    progress: 'verified',
    readiness: 'Ready',
    reference: 'workspace_s3_hub.html',
    section: 'Guide links',
  },
  heroFilters: {
    apis: [
      { contract: 'accepted', method: 'GET', path: '/api/v2/buckets?cursor=&sort=&limit=&q=' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/buckets/stats' },
      { contract: 'accepted', method: 'GET', path: '/api/v2/buckets/filters' },
      { contract: 'missing', method: 'GET', path: '/api/v2/search?q=&types=projects,domains,...' },
      { contract: 'missing', method: 'POST', path: '/api/v2/buckets' },
    ],
    blockers: [
      'Missing accepted response contract for shared global search; the header search remains a shared-shell blocked affordance.',
      'Missing accepted response contract and behavior for POST /api/v2/buckets; the create CTA remains disabled.',
      'Accepted stats payload does not expose the reference visibility stat; accept the contract-backed quota stat as equivalent or provide that exact stat contract.',
    ],
    evidence:
      'Summary values and filter chips use accepted bucket stats, filters, and list payloads.',
    fieldsUsed: [
      'data.totalBuckets',
      'data.totalUsedBytes',
      'data.totalQuotaBytes',
      'data.boundProjectCount',
      'types[].value',
      'types[].count',
      'statuses[].value',
      'statuses[].count',
      'page.total',
    ],
    id: 'bucket-hub-hero-filters',
    nextAction:
      'Provide the shared search contract, bucket create behavior, and a stat-equivalence decision.',
    page: 'Bucket Hub',
    progress: 'in-progress',
    readiness: 'Blocked',
    reference: 'workspace_s3_hub.html',
    section: 'Hero summary / filters',
  },
  tips: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/panels/tips?surface=buckets' }],
    evidence: 'User-provided sample payload is accepted and rendered through React Query.',
    fieldsUsed: ['title', 'description', 'rows[].title', 'rows[].meta', 'footerLink.href'],
    id: 'bucket-hub-tips',
    page: 'Bucket Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_s3_hub.html',
    section: 'Bucket operation tips',
  },
  usageRail: {
    apis: [{ contract: 'accepted', method: 'GET', path: '/api/v2/buckets/panels/usage' }],
    evidence: 'User-provided sample payload is accepted and rendered through React Query.',
    fieldsUsed: [
      'items[].id',
      'items[].name',
      'items[].usedBytes',
      'items[].quotaBytes',
      'items[].usagePercent',
      'summary.usedBytes',
      'summary.quotaBytes',
    ],
    id: 'bucket-hub-usage-rail',
    page: 'Bucket Hub',
    progress: 'implemented',
    readiness: 'Ready',
    reference: 'workspace_s3_hub.html',
    section: 'Usage rail',
  },
} satisfies Record<string, SectionStatusInfo>;
